### ISSUE TITLE
NSTimer结合YYTextWeakProxy会崩溃，导致timer不执行

### ISSUE THREAD

**Issue by GKWenBo** [jezzmemo/JJException#102]
**Describe the bug**

// MARK: - getter
- (NSTimer *)timer {
    if (!_timer) {
        YYTextWeakProxy *weakProxy = [[YYTextWeakProxy alloc] initWithTarget:self];
        _timer = [NSTimer scheduledTimerWithTimeInterval:300
                                                  target:weakProxy
                                                selector:@selector(handleOnline:)
                                                userInfo:nil
                                                 repeats:YES];
        [[NSRunLoop currentRunLoop] addTimer:_timer forMode:NSRunLoopCommonModes];
    }
    return _timer;
}

![截屏2021-05-12 上午11 24 37](https://user-images.githubusercontent.com/25070098/117913918-dc334f00-b314-11eb-980e-3b9674ff0417.png)

**Please complete the following information**
 - Device: iPhoneX
 - OS: iOS13.4
 - Version 0.29

**Comment by jezzmemo** [comment]
#90 原因是一样的
