### ISSUE TITLE
NSMutableAttributedString 的 setAttributes:range: 方法，其中attrs可以为nil

### ISSUE THREAD

**Issue by git4jwb** [jezzmemo/JJException#103]
你好，NSMutableAttributedString 的 setAttributes:range: 方法，其中attrs可以为nil，不需要在hookSetAttributes:range:进行判空拦截了吧
```
@interface NSMutableAttributedString : NSAttributedString

- (void)setAttributes:(nullable NSDictionary<NSAttributedStringKey, id> *)attrs range:(NSRange)range;

@end
```

**Comment by jezzmemo** [comment]
从官方的定义来看是nullable的，api的角度来说是可以为空的，确认没问题后，我会发布新版本

**Comment by jezzmemo** [comment]
https://github.com/jezzmemo/JJException/commit/8b689cf0aaf12f8b5aa0d40dd7fb2c08a7ab7cd2
