### ISSUE TITLE
iOS15下UITextField设置secureTextEntry为YES时，会拦截打印：NSAttributedString enumerateAttributesInRange range:{9223372036854775807, 0}

### ISSUE THREAD

**Issue by git4jwb** [jezzmemo/JJException#110]
**Describe the bug**
iOS15下，UITextField设置secureTextEntry为YES时，会拦截打印：NSAttributedString enumerateAttributesInRange range:{9223372036854775807, 0}。
如果关闭JJException，实际上并不会崩溃。
感觉是iOS15上新增的NSTextContentManager的锅，我暂时没有分析出来，希望大神帮看看，谢谢啦~~

 - Device: 不限
 - OS: iOS15
 - Version：0.2.10

![image](https://user-images.githubusercontent.com/15827381/134315647-58cda468-04ac-4ba7-b143-55dc78e92999.png)

**Comment by lz156** [comment]
同样遇到了

**Comment by git4jwb** [comment]
0.2.11 验证已解决
