### ISSUE TITLE
pod 安装后报错

### ISSUE THREAD

**Issue by SunBoyXiao** [jezzmemo/JJException#113]
![image](https://user-images.githubusercontent.com/6668186/137429537-7dec1418-e204-4145-91e4-ab0af1652e85.png)

**Comment by SunBoyXiao** [comment]
> pod,Xcode,版本号

找到问题，是与项目中其他的第三方同名了。

**Comment by jezzmemo** [comment]
难道有一份从JJException fork出来的代码？这个重名的可能性很小
