### ISSUE TITLE
优量汇广告无法倒计时

### ISSUE THREAD

**Issue by HelloCCCCC** [jezzmemo/JJException#114]
定时器为何会被拦截

JJException Type:64
JJException Description:Need invalidate timer from target:GDTWeakTimerTarget method:GDTfunctionl5ztar:
JJException Extra info:(null)

JJException CallStack:(
	0   JJException                         0x000000010629edc4 -[JJExceptionProxy handleCrashException:exceptionCategory:extraInfo:] + 112
	1   JJException                         0x000000010629ea08 _Z20handleCrashException24JJExceptionGuardCategoryP8NSString + 96
	2   JJException                         0x00000001062a5f60 -[TimerObject fireTimer] + 264

)

**Comment by HelloCCCCC** [comment]
Swift4，GDTMobSDK (4.13.22)，iOS版本(15.0，14.2)

**Comment by zqzal** [comment]
我把NSTimer的统计删除了，就是因为GDT这个问题，你那里有解决吗？
