### ISSUE TITLE
这种情况

### ISSUE THREAD

**Issue by lzc1022** [jezzmemo/JJException#115]
NSString *st = nil;
    NSString *hh = @"h";
    [hh stringByAppendingString:st];
闪退 不触发保活机制 (在不知道st为nil的情况下),请修复

**Comment by jezzmemo** [comment]
不触发保活机制是什么意思？不打开保护？

**Comment by lzc1022** [comment]
是的，直接闪退

**Comment by jezzmemo** [comment]
不打开保护，我无法介入，怎么保护呢

**Comment by lzc1022** [comment]
保证APP不闪退啊 stringByAppendingString这个类型没有添加吧
