### ISSUE TITLE
demo 闪退

### ISSUE THREAD

**Issue by fengyun911** [jezzmemo/JJException#13]
Class currentClass = self.class;
    
    //Check black list
    if (![[[JJExceptionProxy shareExceptionProxy] blackClassesSet] containsObject:currentClass]) {
        [self hookDealloc];
        return;
    }
    
 点击stop guard 闪退   - (void)hookDealloc 死循环
在IOS 12  xcode  10.0

**Comment by jezzmemo** [comment]
我刚刚特地在Xcode10和iOS12测试过了，没有你说的问题，能否把出错信息贴出来，这样我比较好定位

@fengyun911
