### ISSUE TITLE
调用 preparewithInvocationTarget: 崩溃

### ISSUE THREAD

**Issue by Mx-Iris** [jezzmemo/JJException#130]
调用 preparewithInvocationTarget: 方法的时候崩在这个地方了
<img width="1204" alt="Xnip2022-11-26_20-16-56" src="https://user-images.githubusercontent.com/61279231/204088724-433cbb40-c161-4e7c-bbdd-5579dcae4e5b.png">
<img width="1242" alt="Xnip2022-11-26_20-16-31" src="https://user-images.githubusercontent.com/61279231/204088728-75441037-30d5-4192-aab6-5dff285c2751.png">

**Comment by jezzmemo** [comment]
看起来像是内存的问题导致的，有没稳定复现的方法？

**Comment by Mx-Iris** [comment]
> 看起来像是内存的问题导致的，有没稳定复现的方法？

我看代码崩的地方是在JJException MRC文件夹中的代码，我现在这个项目能复现，但是是公司的项目，我看看怎么抽出一个Demo来，我换成RegiseterUndo就不会崩溃了，prepare必崩
