### ISSUE TITLE
KVOCrash与AFN搭配会有概率闪退

### ISSUE THREAD

**Issue by msh940620** [jezzmemo/JJException#14]
**Describe the bug**
在didFinishLaunchingWithOptions启动startGuardException（含有JJExceptionGuardKVOCrash）与发起网络请求，有一定概率在AFURLSessionManager  142行
progress.totalUnitCount = NSURLSessionTransferSizeUnknown; 崩溃（Thread 1: EXC_BAD_ACCESS）
configExceptionCategory 不含 JJExceptionGuardKVOCrash 则正常
具体闪退规律暂没有找到
**Please complete the following information**
 - Device: [e.g. iPhoneSE]
 - OS: [e.g. iOS12.0.1]

**Comment by jezzmemo** [comment]
请说下，你的AFNetworking和JJException的版本

@msh940620

**Comment by msh940620** [comment]
AFNetworking (3.2.1)，
JJException (0.1.0):
非常感谢。

**Comment by jezzmemo** [comment]
这是我的测试，代码:
```
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
    
    dispatch_queue_t queue = dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0);


    dispatch_apply(100, queue, ^(size_t i){
        [self test];

    });

    [JJException configExceptionCategory:JJExceptionGuardAll];
    [JJException startGuardException];
    
    return YES;
}

- (void)test{
    
    dispatch_async(dispatch_get_main_queue(), ^void{
        NSURLSessionConfiguration *configuration = [NSURLSessionConfiguration defaultSessionConfiguration];
        AFURLSessionManager *manager = [[AFURLSessionManager alloc] initWithSessionConfiguration:configuration];
        
        NSURL *URL = [NSURL URLWithString:@"http://httpbin.org/get"];
        NSURLRequest *request = [NSURLRequest requestWithURL:URL];
        
        NSURLSessionDataTask *dataTask = [manager dataTaskWithRequest:request completionHandler:^(NSURLResponse *response, id responseObject, NSError *error) {
            if (error) {
                NSLog(@"Error: %@", error);
            } else {
                NSLog(@"%@ %@", response, responseObject);
            }
        }];
        [dataTask resume];
    });
    
}
```

没有重现，能否把你的代码贴出来，或者你能把这个错误偶尔闪退的代码贴出来，对了，你是在真机上比较好重现？
@msh940620

**Comment by msh940620** [comment]
目前都是真机触发，而且很随机，目前也很难稳定触发，具体原因还没定位到。
触发闪退目前是在项目启动广告页中加载后台数据时出现的，进入桌面之后目前是稳定的。
项目启动中我用的是XHLaunchAd。
这个是崩溃时的调用堆栈。
<img width="533" alt="309b563b-4c82-4e3f-893c-c75234e196f8" src="https://user-images.githubusercontent.com/15317891/47152920-9bb3f600-d310-11e8-89b9-74c7ea5c20d6.png">
我这几天多测试下这个问题，看能不能单独抽出来个demo。
非常感谢您的回复。

**Comment by msh940620** [comment]
问题已经确认，是后台加载数据导致的，是后台请求队列已经启动还未结束的期间startGuardException。导致这队列中某次网络请求kvo异常崩溃。目前把startGuardException移进didFinishLaunchingWithOptions最先启动项目目前没发现异常。文档可以建议开发者把启动代码放到- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions 中优先处理。非常感谢。

**Comment by jezzmemo** [comment]
谢谢你的提醒，我之前也有思考过这个问题，有种场景就是执行到一半，JJException生效了，这个时候就异常了，所以之前我是用的无侵入式好处就是在load方法执行，但是不够灵活和显示，后续我在文档会更新下这个问题
@msh940620

**Comment by acekiller** [comment]
@jezzmemo 对于这个问题在0.1.6仍然存在哟。对这个问题我提了个issue，其中跟到了在10.3.3存在重复的kvo被remove的的出现。但由于runtime运行时的干扰，跟踪起来比较麻烦。还有就是可以考虑多线程情况+特定系统版本下，采用真机，应该比较容易复现。
