### ISSUE TITLE
RAC

### ISSUE THREAD

**Issue by BinBear** [jezzmemo/JJException#16]
这个库跟RAC是否能兼容呢

**Comment by jezzmemo** [comment]
这个我没测试，稍后我可以测试下，如果你们用过，方便的话给一个测试结果
@BinBear

**Comment by jezzmemo** [comment]
我刚刚简单的测试了下RAC的Objective-c版本，没啥大问题，当然我没有深入测试，如果后续有问题，欢迎提出来
@BinBear

**Comment by jezzmemo** [comment]
最近发现确实存在冲突，并已经修复

#26
