### ISSUE TITLE
有Swift版本的吗？

### ISSUE THREAD

**Issue by WuXiaoTu** [jezzmemo/JJException#17]
有Swift版本的吗？

**Comment by jezzmemo** [comment]
JJException的技术原理主要通过Objective-c 的Runtime技术做到的，如果你的项目是纯swift，swift的特性是不支持runtime的，所以JJException在纯Swift的项目没啥作用。主要在以下的工程中有作用:
1.Swift和Objective-c混编
2.纯Objective-c

@WuXiaoTu

**Comment by WuXiaoTu** [comment]
我就是Swift和OC混编的，但是建工程的时候是用Swift建的，里面也有很多OC的代码！ 










在 2018-10-23 11:08:32，"jezz" <notifications@github.com> 写道：


JJException的技术原理主要通过Objective-c 的Runtime技术做到的，如果你的项目是纯swift，swift的特性是不支持runtime的，所以JJException在纯Swift的项目没啥作用。主要在以下的工程中有作用:
1.Swift和Objective-c混编
2.纯Objective-c

@WuXiaoTu

**Comment by WuXiaoTu** [comment]
好的，明白了，我也用pod引入试一下，感谢作者！！










在 2018-10-23 14:22:11，"jezz" <notifications@github.com> 写道：


这是Swift的示例，我是用Pod引入的:

importUIKitimportJJException@UIApplicationMainclassAppDelegate: UIResponder, UIApplicationDelegate,JJExceptionHandle {

    var window: UIWindow?funcapplication(_application: UIApplication, didFinishLaunchingWithOptionslaunchOptions: [UIApplication.LaunchOptionsKey: Any]?) ->Bool {
        self.registerJJException()
        returntrue
    }
    
    funcregisterJJException(){
        JJException.configExceptionCategory(.all)
        JJException.startGuard()
        JJException.register(self);
    }
    
    funchandleCrashException(_exceptionMessage: String, extraInfoinfo: [AnyHashable : Any]?) {
        
    }
}

**Comment by WuXiaoTu** [comment]
Swift和OC混编是不是只以OC代码有效啊！ 我刚集成了进去，在Swift页面随便写了一个数组越界，没有效果！ 








在 2018-10-23 14:53:16，"jezz" <notifications@github.com> 写道：


Closed #17.

**Comment by jezzmemo** [comment]
你没仔细看我说的，我这个比较是针对objective-c代码的，你可以用objective-c代码测试，上面初始化代码，只是用swift代码来初始化和启动，不能对swift异常拦截

**Comment by WuXiaoTu** [comment]
哦，明白了！ thank s










在 2018-10-23 15:11:11，"jezz" <notifications@github.com> 写道：


你没仔细看我说的，我这个比较是针对objective-c代码的，你可以用objective-c代码测试，上面初始化代码，只是用swift代码来初始化和启动，不能对swift异常拦截
