### ISSUE TITLE
是不是得每个VC都要去实现JJExceptionHandle破获crash信息，这样会很麻烦吧

### ISSUE THREAD

**Issue by luoerming** [jezzmemo/JJException#19]
有无方法可以全局收集的，例如在根控制器里面实现统一收集？

**Comment by jezzmemo** [comment]
这个理解有点问题，我的设计是，你需要放在一个活的实例化对象里，实现一个就够了，任何错误都往这个delegate发送，然后由Application来处理这些错误信息
@luoerming

**Comment by luoerming** [comment]
明白了，我放在根控制器里实例化了，谢谢！可关闭 issue
