### ISSUE TITLE
COCOAPODS 不是最新版本？头文件都没有startGuardException方法

### ISSUE THREAD

**Issue by luoerming** [jezzmemo/JJException#20]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by jezzmemo** [comment]
引入这个头文件即可:
```
#import <JJException/JJException.h>
```

**Comment by luoerming** [comment]
> 引入这个头文件即可:
> 
> ```
> #import <JJException/JJException.h>
> ```

不是这头文件引用问题这应该是你没更新cocoapods的版本，根这个方法 `No known class method for selector 'configExceptionCategory:'`

**Comment by jezzmemo** [comment]
麻烦告知下，你的Cocoapods和JJException,我本地用的Cocoapods1.5.3，最新的JJException是0.1.1

@luoerming

**Comment by jezzmemo** [comment]
我知道为什么了，你的本地repo太老了，你在install之前执行:
```
pod repo update
```
在pod install就好了

**Comment by luoerming** [comment]
> 我知道为什么了，你的本地repo太老了，你在install之前执行:
> 
> ```
> pod repo update
> ```
> 在pod install就好了

Wow, 非常感谢呢，我没留意这里的提示信息，本地仓库太就没更新啦，谢谢你啦；
