### ISSUE TITLE
请问下，我需要全局将崩溃日志上传到bugly上去，怎么只写一个回传方法，而不是每一个控制器里实现协议

### ISSUE THREAD

**Issue by TYQbag** [jezzmemo/JJException#23]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by jezzmemo** [comment]
实现这个协议，你可以在任意地方，只要这个地方是实例化并存活的，就可以，我只是一个示例而已

**Comment by TYQbag** [comment]
好的，我刚刚实践了一把，我发现只要我的APP在前台触发这个崩溃，协议就会调用很多次，我断电的是15次以上，我这样频繁的向bugly发送错误信息会出问题吧

**Comment by TYQbag** [comment]
所以我很奇怪，为什么会触发这么多次，望大神指教

**Comment by jezzmemo** [comment]
你把错误信息，打印出来，发出来，我看看

@TYQbag

**Comment by TYQbag** [comment]
4340891648
45924352
NSMutableArray addObject nil object
[
	0   Eamp                                0x0000000102de046c -[JJExceptionProxy handleCrashException:exceptionCategory:extraInfo:] + 144,
	1   Eamp                                0x0000000102ddffe8 _Z20handleCrashException24JJExceptionGuardCategoryP8NSString + 120,
	2   Eamp                                0x0000000102de2b3c -[NSMutableArray(MutableArrayHook) hookAddObject:] + 84,
	3   Eamp                                0x0000000103804afc __61-[SessionViewController querySessionsFromServiceiSUpdateApp:]_block_invoke + 1156,
	4   Eamp                                0x00000001036ad870 __67-[ServerEngine serverCallRest:path:params:body:callback:needCache:]_block_invoke + 896,
	5   Eamp                                0x0000000102d5f3ac __72-[AFURLSessionManagerTaskDelegate URLSession:task:didCompleteWithError:]_block_invoke_2.150 + 224,
	6   libdispatch.dylib                   0x0000000104777840 _dispatch_call_block_and_release + 24,
	7   libdispatch.dylib                   0x0000000104778de4 _dispatch_client_callout + 16,
	8   libdispatch.dylib                   0x0000000104786830 _dispatch_main_queue_callback_4CF + 748,
	9   CoreFoundation                      0x00000001b47161bc <redacted> + 12,
	10  CoreFoundation                      0x00000001b4711084 <redacted> + 1964,
	11  CoreFoundation                      0x00000001b47105b8 CFRunLoopRunSpecific + 436,
	12  GraphicsServices                    0x00000001b6984584 GSEventRunModal + 100,
	13  UIKitCore                           0x00000001e1157558 UIApplicationMain + 212,
	14  Eamp                                0x0000000102d0aed0 main + 124,
	15  libdyld.dylib                       0x00000001b41d0b94 <redacted> + 4

**Comment by TYQbag** [comment]
我就随便插入了一个nil到数组里

**Comment by TYQbag** [comment]
触发崩溃调15次以上太恐怖了

**Comment by TYQbag** [comment]
不好意思，我晓得为什么了，我忘了我是在一个循环里面做的
