### ISSUE TITLE
为什么不执行代理方法？

### ISSUE THREAD

**Issue by wfkbyni** [jezzmemo/JJException#25]
#import "WXExceptionController.h"
#import <JJException/JJException.h>

@interface WXExceptionController ()<JJExceptionHandle>

@end

@implementation WXExceptionController

- (void)viewDidLoad {
    [super viewDidLoad];
    self.view.backgroundColor = [UIColor whiteColor];
    self.title = @"异常信息";
    
    [JJException registerExceptionHandle:self];
}

- (void)handleCrashException:(NSString *)exceptionMessage exceptionCategory:(JJExceptionGuardCategory)exceptionCategory extraInfo:(NSDictionary *)info {
    WXLog(@"exceptionMessage: %@\n exceptionCategory: %@\n extraInfo: %@", exceptionMessage, @(exceptionCategory), info)
}

-(void)handleCrashException:(NSString *)exceptionMessage extraInfo:(NSDictionary *)info {
    WXLog(@"exceptionMessage: %@\n extraInfo: %@", exceptionMessage, info)
}

@end

当抛错误时，两个代理方法不会执行，不能记录日志

**Comment by jezzmemo** [comment]
你漏加上设置类型和开启保护:
```
[JJException configExceptionCategory:JJExceptionGuardAll];
[JJException startGuardException];
```
