### ISSUE TITLE
希望处理能加入replaceCharactersInRange越界异常的处理

### ISSUE THREAD

**Issue by msh940620** [jezzmemo/JJException#27]
NSString,NSMutableString,NSAttributedString,NSMutableAttributedString(下标越界以及参数nil异常)
缺少 NSMutableAttributedString   replaceCharactersInRange 越界的拦截
也属于平常常遇到的crash
在用户快速切换语音输入根键盘输入的时候 如果执行这类替换方法会很容易崩，非常感谢

**Comment by jezzmemo** [comment]
谢谢你的建议，后续我添加进来，我是参考我们工程里的闪退的函数来写的，所以估计有些没有覆盖到，最近有时间，我会加入进来

**Comment by msh940620** [comment]
> 谢谢你的建议，后续我添加进来，我是参考我们工程里的闪退的函数来写的，所以估计有些没有覆盖到，最近有时间，我会加入进来
也可以参考下这个https://github.com/lsmakethebest/LSSafeProtector

**Comment by jezzmemo** [comment]
嗯，我会加强一部分，然后会把我支持的函数列表都列出来，这样对开发者比较好查找，也方便记录和补充

**Comment by jezzmemo** [comment]
升级到0.1.3, replaceCharactersInRange已加入支持
@msh940620
