### ISSUE TITLE
老哥出大事了，handleCrashException里面的回调info是空的

### ISSUE THREAD

**Issue by luoerming** [jezzmemo/JJException#28]
以下是  exceptionMessager 内容， 而info是空的;

`lldb) po exceptionMessage
4402061312
107094016
NSArray objectAtIndexedSubscript invalid index:1 total:0
(
	0   xxx                            0x0000000106a30626 -[JJExceptionProxy handleCrashException:exceptionCategory:extraInfo:] + 134,
	1   xxx                            0x0000000106a30200 _Z20handleCrashException24JJExceptionGuardCategoryP8NSString + 96,
	2   xxx                            0x0000000106a31b55 -[NSArray(ArrayHook) hookObjectAtIndexedSubscript:] + 197,
	3   xxx                            0x00000001067777b5 -[TSLStationFilterViewController initialize] + 213,
	4   xxx                            0x00000001067776da -[TSLStationFilterViewController viewDidLoad] + 74,
	5   UIKitCore                           0x00000001170b44e1 -[UIViewController loadViewIfRequired] + 1186,
	6   UIKitCore                           0x00000001170b4940 -[UIViewController view] + 27,
	7   UIKitCore                           0x0000000116ffea9b -[UINavigationController _startCustomTransition:] + 931,
	8   UIKitCore                           0x00000001170153f0 -[UINavigationController _startDeferredTransitionIfNeeded:] + 741,
	9   UIKitCore                           0x00000001170167e0 -[UINavigationController __viewWillLayoutSubviews] + 150,
	10  UIKitCore                           0x0000000116ff6600 -[UILayoutContainerView layoutSubviews] + 217,
	11  UIKit                               0x000000012c09a6c4 -[UILayoutContainerViewAccessibility layoutSubviews] + 42,
	12  UIKitCore                           0x0000000117bbd795 -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 1441,
	13  QuartzCore                          0x000000010c896b19 -[CALayer layoutSublayers] + 175,
	14  QuartzCore                          0x000000010c89b9d3 _ZN2CA5Layer16layout_if_neededEPNS_11TransactionE + 395,
	15  QuartzCore                          0x000000010c8147ca _ZN2CA7Context18commit_transactionEPNS_11TransactionE + 342,
	16  QuartzCore                          0x000000010c84b97e _ZN2CA11Transaction6commitEv + 576,
	17  UIKitCore                           0x00000001176cd701 _UIApplicationFlushRunLoopCATransactionIfTooLate + 165,
	18  UIKitCore                           0x00000001177c7569 __handleEventQueueInternal + 6874,
	19  CoreFoundation                      0x00000001096ad721 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17,
	20  CoreFoundation                      0x00000001096acf93 __CFRunLoopDoSources0 + 243,
	21  CoreFoundation                      0x00000001096a763f __CFRunLoopRun + 1263,
	22  CoreFoundation                      0x00000001096a6e11 CFRunLoopRunSpecific + 625,
	23  GraphicsServices                    0x0000000113ca11dd GSEventRunModal + 62,
	24  UIKitCore                           0x00000001176d381d UIApplicationMain + 140,
	25  TeslaMap                            0x000000010663c5a0 main + 112,
	26  libdyld.dylib                       0x000000010fba2575 start + 1,
	27  ???                                 0x0000000000000001 0x0 + 1,
)
`

**Comment by jezzmemo** [comment]
```
@protocol JJExceptionHandle<NSObject>
- (void)handleCrashException:(NSString*)exceptionMessage extraInfo:(nullable NSDictionary*)info;
@optional
- (void)handleCrashException:(NSString*)exceptionMessage exceptionCategory:(JJExceptionGuardCategory)exceptionCategory extraInfo:(nullable NSDictionary*)info;
@end
```
这个是info的设计的目的，是为了扩展用的，在某些场合需要，暂时没用到

**Comment by luoerming** [comment]
原来是这样，下面有个问题，“KVO forgot remove keyPath:bounds” 这报错是什么原因？没有定位到代码位置


`KVO forgot remove keyPath:bounds
(
	0   TeslaMap                            0x00000001015a9666 -[JJExceptionProxy handleCrashException:exceptionCategory:extraInfo:] + 134,
	1   TeslaMap                            0x00000001015a9240 _Z20handleCrashException24JJExceptionGuardCategoryP8NSString + 96,
	2   TeslaMap                            0x00000001015ae0ec -[KVOObjectContainer clearKVOData] + 412,
	3   TeslaMap                            0x00000001015adebc -[KVOObjectContainer dealloc] + 44,
	4   libobjc.A.dylib                     0x00000001078ebdcc _ZN11objc_object17sidetable_releaseEb + 202,
	5   libobjc.A.dylib                     0x00000001078e8bbe _object_remove_assocations + 353,
	6   libobjc.A.dylib                     0x00000001078e413b objc_destructInstance + 153,
	7   libobjc.A.dylib                     0x00000001078e4161 object_dispose + 22,
	8   TeslaMap                            0x00000001015af6e7 -[NSObject(ZombieHook) hookDealloc] + 135,
	9   UIKitCore                           0x00000001122ea73a -[UIResponder dealloc] + 145,
	10  UIKit                               0x0000000126beb6ce -[UIResponderAccessibility dealloc] + 55,
	11  UIKitCore                           0x0000000112777670 -[UIView dealloc] + 1041,
	12  Foundation                          0x00000001053cfeb0 NSKVODeallocate + 158,
	13  libobjc.A.dylib                     0x00000001078ec4c7 _ZN12_GLOBAL__N_119AutoreleasePoolPage3popEPv + 795,
	14  UIKitCore                           0x000000011277764f -[UIView dealloc] + 1008,
	15  UIKitCore                           0x000000011209fb59 -[UIInputSetContainerView dealloc] + 104,
	16  UIKitCore                           0x0000000111c9a7c0 -[UIViewController dealloc] + 661,
	17  UIKitCore                           0x00000001120a0fc8 -[UIInputWindowController dealloc] + 837,
	18  CoreFoundation                      0x0000000104343d0d -[__NSArrayI dealloc] + 61,
	19  libobjc.A.dylib                     0x00000001078ebdcc _ZN11objc_object17sidetable_releaseEb + 202,
	20  UIKitCore                           0x00000001122c925d _runAfterCACommitDeferredBlocks + 713,
	21  UIKitCore                           0x00000001122b7b2c _cleanUpAfterCAFlushAndRunDeferredBlocks + 384,
	22  UIKitCore                           0x00000001122e6efc _afterCACommitHandler + 135,
	23  CoreFoundation                      0x0000000104225c27 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 23,
	24  CoreFoundation                      0x00000001042200be __CFRunLoopDoObservers + 430,
	25  CoreFoundation                      0x0000000104220751 __CFRunLoopRun + 1537,
	26  CoreFoundation                      0x000000010421fe11 CFRunLoopRunSpecific + 625,
	27  GraphicsServices                    0x000000010e81a1dd GSEventRunModal + 62,
	28  UIKitCore                           0x00000001122bd81d UIApplicationMain + 140,
	29  TeslaMap                            0x00000001011b5690 main + 112,
	30  libdyld.dylib                       0x000000010a71b575 start + 1,
	31  ???                                 0x0000000000000001 0x0 + 1,
)

(lldb) `

**Comment by luoerming** [comment]
是提示我忘记移出KVO？因为这个回调里面的信息我都要上报bugly，如只是提示或警告信息也要上报那我的bugly错误率就要爆了；

**Comment by jezzmemo** [comment]
这个不是警告，如果不处理，在ios8,9我确定会闪退，只是JJException帮你处理了。
handleCrashException是记录可能闪退的地方，不是警告哦。

**Comment by luoerming** [comment]
OK感谢你啦，但这里我无法定位具体位置？请问如何分析这些信息；

**Comment by jezzmemo** [comment]
bounds全局搜索一遍，后续我想办法把当前的类名要给出，这样好定位

**Comment by luoerming** [comment]
好，有类型就简单多了，但是我现在没有关键字定位，如何搜

**Comment by jezzmemo** [comment]
Command + 4

**Comment by msh940620** [comment]
这个如果不处理肯定是会闪退的。不过有一部分第三方库是在自己内部实现了对自己kvo的异常处理，所以之前可能线上不出现崩溃，但是在handleCrashException中会被拦截处理，我这边的处理是异常上报把JJExceptionGuardNSTimer根JJExceptionGuardKVOCrash排除

**Comment by luoerming** [comment]
> 这个如果不处理肯定是会闪退的。不过有一部分第三方库是在自己内部实现了对自己kvo的异常处理，所以之前可能线上不出现崩溃，但是在handleCrashException中会被拦截处理，我这边的处理是异常上报把JJExceptionGuardNSTimer根JJExceptionGuardKVOCrash排除

可以的，我的比较简单粗暴，直接 。。。。
`if (exceptionMessage && ![exceptionMessage containsString:@"KVO forgot remove"]) {`

**Comment by luoerming** [comment]
> > > 这个如果不处理肯定是会闪退的。不过有一部分第三方库是在自己内部实现了对自己kvo的异常处理，所以之前可能线上不出现崩溃，但是在handleCrashException中会被拦截处理，我这边的处理是异常上报把JJExceptionGuardNSTimer根JJExceptionGuardKVOCrash排除
> > 
> > 
> > 可以的，我的比较简单粗暴，直接 。。。。
> > `if (exceptionMessage && ![exceptionMessage containsString:@"KVO forgot remove"]) {`
> 
> 你别忽略这个exception啊，你升级到0.1.3版本，加入了显示是那个类的KVO，来处理这个错误
> 
> @luoerming

好的，感谢老哥，另外可以帮我看下，我已经升了0.13但还是没办法定位具体位置，可以帮我看一下吗？

`
KVO forgot remove keyPath:frame from which object:NSKVONotifying_UIInputSetHostView
(
	0   xxx                            0x0000000109ba66e6 -[JJExceptionProxy handleCrashException:exceptionCategory:extraInfo:] + 134,
	1   xxx                            0x0000000109ba62c0 _Z20handleCrashException24JJExceptionGuardCategoryP8NSString + 96,
	2   xxx                            0x0000000109bab921 -[KVOObjectContainer clearKVOData] + 465,
	3   xxx                            0x0000000109bab6bc -[KVOObjectContainer dealloc] + 44,
	4   libobjc.A.dylib                     0x000000010feebdcc _ZN11objc_object17sidetable_releaseEb + 202,
	5   libobjc.A.dylib                     0x000000010fee8bbe _object_remove_assocations + 353,
	6   libobjc.A.dylib                     0x000000010fee413b objc_destructInstance + 153,
	7   libobjc.A.dylib                     0x000000010fee4161 object_dispose + 22,
	8   xxx                            0x0000000109bacff7 -[NSObject(ZombieHook) hookDealloc] + 135,
	9   UIKitCore                           0x000000011a87973a -[UIResponder dealloc] + 145,
	10  UIKit                               0x000000012f1eb6ce -[UIResponderAccessibility dealloc] + 55,
	11  UIKitCore                           0x000000011ad06670 -[UIView dealloc] + 1041,
	12  Foundation                          0x000000010d9cfeb0 NSKVODeallocate + 158,
	13  libobjc.A.dylib                     0x000000010feec4c7 _ZN12_GLOBAL__N_119AutoreleasePoolPage3popEPv + 795,
	14  UIKitCore                           0x000000011ad0664f -[UIView dealloc] + 1008,
	15  UIKitCore                           0x000000011a62eb59 -[UIInputSetContainerView dealloc] + 104,
	16  UIKitCore                           0x000000011a2297c0 -[UIViewController dealloc] + 661,
	17  UIKitCore                           0x000000011a62ffc8 -[UIInputWindowController dealloc] + 837,
	18  CoreFoundation                      0x000000010c943d0d -[__NSArrayI dealloc] + 61,
	19  libobjc.A.dylib                     0x000000010feebdcc _ZN11objc_object17sidetable_releaseEb + 202,
	20  UIKitCore                           0x000000011a85825d _runAfterCACommitDeferredBlocks + 713,
	21  UIKitCore                           0x000000011a846b2c _cleanUpAfterCAFlushAndRunDeferredBlocks + 384,
	22  UIKitCore                           0x000000011a875efc _afterCACommitHandler + 135,
	23  CoreFoundation                      0x000000010c825c27 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 23,
	24  CoreFoundation                      0x000000010c8200be __CFRunLoopDoObservers + 430,
	25  CoreFoundation                      0x000000010c820751 __CFRunLoopRun + 1537,
	26  CoreFoundation                      0x000000010c81fe11 CFRunLoopRunSpecific + 625,
	27  GraphicsServices                    0x0000000116ebf1dd GSEventRunModal + 62,
	28  UIKitCore                           0x000000011a84c81d UIApplicationMain + 140,
	29  xxx                            0x00000001097b1080 main + 112,
	30  libdyld.dylib                       0x0000000112d1b575 start + 1,
	31  ???                                 0x0000000000000001 0x0 + 1,
)
`

**Comment by jezzmemo** [comment]
我看了下你的callstack，是系统调用，应该是跟键盘有关系，你能否说下，你的使用场景，我来模拟下看看能否重现，最近你有个简单的demo给我，这样我比较好找问题
@luoerming

**Comment by luoerming** [comment]
> 我看了下你的callstack，是系统调用，应该是跟键盘有关系，你能否说下，你的使用场景，我来模拟下看看能否重现，最近你有个简单的demo给我，这样我比较好找问题
> @luoerming

老哥抱歉，昨天一直在忙，是这样的那个报错确实是有键盘，我公司的项目代码比较杂乱不好抽出来，我大概贴一点你看下；


TSLSearchViewController:

`-(void)viewWillDisappear:(BOOL)animated
{
    [self.searchView endActive];
    [super viewWillDisappear:animated];
}
`

---

TSLSearchView:

`

#import "TSLSearchView.h"

@interface TSLSearchView ()<UITextFieldDelegate>
{
    BOOL _hasResponsToShouldChangeString;
}

@property (nonatomic, strong) UIImageView *iconView;

@property (nonatomic, copy) void (^clickedBlock)(void);

@end

@implementation TSLSearchView

-(void)dealloc
{
    _clickedBlock = nil;
}


-(instancetype)initWithFrame:(CGRect)frame
              showSearchIcon:(BOOL)showIcon
{
    if (self = [super initWithFrame:frame]) {
        self.backgroundColor = WhiteColor;
        
        if (showIcon) {
            [self addSubview:self.iconView];
            [self.iconView mas_makeConstraints:^(MASConstraintMaker *make) {
                make.left.equalTo(self).with.offset(15);
                make.centerY.equalTo(self);
                make.width.equalTo(@(self.iconView.width));
                make.height.equalTo(@(self.iconView.height));
            }];
        }
        
        [self addSubview:self.textField];
        [self.textField mas_makeConstraints:^(MASConstraintMaker *make) {
            if (showIcon) {
                make.left.equalTo(self).with.offset(kSearchBarHeight + 10);
            }else{
                make.left.equalTo(self).with.offset(10);
            }
            
            make.top.bottom.equalTo(self);
            make.right.equalTo(self).with.offset(-10);
        }];
    }
    
    return self;
}

-(void)setPlaceholder:(NSString *)placeholder
{
    NSMutableAttributedString *attPlaceholder = [[NSMutableAttributedString alloc] initWithString:placeholder];
    [attPlaceholder addAttribute:NSForegroundColorAttributeName
                           value:GrayTitleColor
                           range:NSMakeRange(0, attPlaceholder.length)];
    [attPlaceholder addAttribute:NSFontAttributeName
                           value:Font(14)
                           range:NSMakeRange(0, attPlaceholder.length)];
    [self.textField setAttributedPlaceholder:attPlaceholder];
}


-(void)setClickedSearchViewBlock:(void (^)())block
{
    self.textField.userInteractionEnabled = NO;
    _clickedBlock = block;
    
    [self addTapAction:@selector(clickedSearchView) target:self];
}


-(void)checkDelegate
{
    if (self.delegate && [self.delegate respondsToSelector:@selector(searchViewShouldChangeToString:)]) {
        _hasResponsToShouldChangeString = YES;
    }
}


-(void)becomeActive
{
    [self.textField becomeFirstResponder];
}

-(void)endActive
{
    [self.textField resignFirstResponder];
}


-(void)clearText
{
    self.textField.text = @"";
}


#pragma mark - button actions

- (void)clickedSearchView
{
    if (_clickedBlock) {
        _clickedBlock();
    }
}


#pragma mark - UITextFieldDelegate

-(BOOL)textFieldShouldBeginEditing:(UITextField *)textField
{
    if (self.delegate && [self.delegate respondsToSelector:@selector(searchViewShouldBeginEditing)]) {
        return [self.delegate searchViewShouldBeginEditing];
    }
    
    return YES;
}



- (BOOL)textField:(UITextField *)textField shouldChangeCharactersInRange:(NSRange)range replacementString:(NSString *)string
{
    NSString *newString = [textField.text stringByReplacingCharactersInRange:range withString:string];
    if (_hasResponsToShouldChangeString) {
        [self.delegate searchViewShouldChangeToString:newString];
    }
    
    return YES;
}


-(BOOL)textFieldShouldClear:(UITextField *)textField
{
    if (self.delegate && [self.delegate respondsToSelector:@selector(searchViewShouldClear)]) {
        [self.delegate searchViewShouldClear];
    }
    
    return YES;
}


-(BOOL)textFieldShouldReturn:(UITextField *)textField
{
    if (self.delegate && [self.delegate respondsToSelector:@selector(searchViewShouldReturn:)]) {
        [self.delegate searchViewShouldReturn:textField];
    }
    
    return YES;
}

#pragma mark - 懒加载

-(UIImageView *)iconView
{
    if (!_iconView) {
        UIImage *image = [UIImage imageNamed:@"search"];
        _iconView = [[UIImageView alloc] initWithFrame:CGRectMake(0, 0, image.size.width, image.size.height)];
        _iconView.image = image;
    }
    
    return _iconView;
}

-(UITextField *)textField
{
    if (!_textField) {
        _textField = [[UITextField alloc] initWithFrame:CGRectZero];
        _textField.textColor = [UIColor blackColor];
        _textField.font = Font(15);
        _textField.clearButtonMode = UITextFieldViewModeWhileEditing;
        _textField.returnKeyType = UIReturnKeySearch;
        
        _textField.delegate = self;
    }
    
    return _textField;
}


`

**Comment by jezzmemo** [comment]
@luoerming 这里面有两个点，一个就是键盘弹出，一个就是Masonry，我简单测试过了，没有问题，你要把你的运行环境跟我说下，看看是否是环境的问题

**Comment by luoerming** [comment]
Version  (10B61)

> @luoerming 这里面有两个点，一个就是键盘弹出，一个就是Masonry，我简单测试过了，没有问题，你要把你的运行环境跟我说下，看看是否是环境的问题

运行环境？我xcode 10.1
