### ISSUE TITLE
你好,kvo拦截时出现一个问题

### ISSUE THREAD

**Issue by yaomars** [jezzmemo/JJException#29]
- (void)clearKVOData{
    for (KVOObjectItem* item in self.kvoObjectSet) {
        //Invoke the origin removeObserver,do not check array
        handleCrashException(YJExceptionGuardKVOCrash,[NSString stringWithFormat:@"KVO forgot remove keyPath:%@ from which object:%@",item.keyPath,NSStringFromClass(object_getClass(self.whichObject))]);
        #pragma clang diagnostic push
        #pragma clang diagnostic ignored "-Wundeclared-selector"
        @try {
            ((void(*)(id,SEL,id,NSString*))objc_msgSend)(self.whichObject,@selector(hookRemoveObserver:forKeyPath:),item.observer,item.keyPath);
        }@catch (NSException *exception) {
            handleCrashException(YJExceptionGuardKVOCrash,[exception reason]);
        }
        #pragma clang diagnostic pop
    }
}

![image](https://user-images.githubusercontent.com/18243933/48413919-28bd6400-e784-11e8-8833-947dd8113688.png)

会在object_getClass(self.whichObject) 崩溃,麻烦看下

**Comment by jezzmemo** [comment]
这个问题是我的疏忽，我之前解决过这个问题，0.1.3更新的时候疏忽了，0.1.4我马上修复这个问题

**Comment by jezzmemo** [comment]
是因为我是assign的observer，因为用的AssociatedObject原理来释放的，这个时候有可能observer对方释放了，这个去取这个指针的信息，就是野指针了。
