### ISSUE TITLE
MGIsDeviceOneOfType is not supported on this platform

### ISSUE THREAD

**Issue by Liqiankun** [jezzmemo/JJException#3]

**Comment by jezzmemo** [comment]
请问下，这个错误信息怎么弄出来的，请详细说明下，这样我好答复你
@Liqiankun

**Comment by Liqiankun** [comment]
好的，只要我在Xcode 10中运行就会出现这个错误！[mgisdeviceoneoftyp](https://stackoverflow.com/questions/50701321/xcode-error-on-simulation)

**Comment by jezzmemo** [comment]
加入不引入JJException这个，就不会报错？我可以这么理解？

**Comment by Liqiankun** [comment]
我下载了项目，直接运行，就是这个错误！

**Comment by jezzmemo** [comment]
稍后我用xcode 10来试试，对了，你用pod引入试试，看看有没类似的问题

**Comment by jezzmemo** [comment]
刚刚试试了下，用Xcode 10打开工程在模拟器是可以运行的，因为这个错误和我本身的功能没啥关联，只能怀疑Xcode 10的环境问题
@Liqiankun
