### ISSUE TITLE
当originIMP不等于currentClassIMP时为什么return nil?

### ISSUE THREAD

**Issue by wang-yapu** [jezzmemo/JJException#31]
我在读你的源码,有个地方不太理解: 

[链接](https://github.com/jezzmemo/JJException/blob/ad520acb2a42976a6f24b3fff156ec5af8e1029c/JJException/Source/MRC/NSObject%2BUnrecognizedSelectorHook.m#L32)

NSObject+UnrecognizedSelectorHook.m --> methodSignatureForSelectorSwizzled --> 32行
```
    // If current class override methodSignatureForSelector return nil
    if (originIMP != currentClassIMP){
        return nil;
    }
```

这里返回nil的话,不就直接crash了吗?

**Comment by jezzmemo** [comment]
证明父类重写了，需要扔给父类处理

**Comment by wang-yapu** [comment]
重写了哪个方法?  我直观理解您说的是methodSignatureForSelector, 可是父类如果重写了methodSignatureForSelector的话,在第24行不就return掉了吗?

```
NSMethodSignature* methodSignature = [self methodSignatureForSelectorSwizzled:aSelector];
    if (methodSignature) {
        return methodSignature;
    }
```

**Comment by jezzmemo** [comment]
应该这么理解,[self methodSignatureForSelectorSwizzled:aSelector]是检查aSelector是否存在,如果不存在才会到
```
 if (originIMP != currentClassIMP){
        return nil;
    }
```
这个流程,这里检查当前methodSignatureForSelector的IMP和NSObject的methodSignatureForSelector对应的IMP,如果一样，证明没有被当前类重写，如果不一样，证明当前类重写了，返回nil时为了给重写的部分来实现自己的需求.
