### ISSUE TITLE
kvo removeobser冲突 with ios 10.x

### ISSUE THREAD

**Issue by acekiller** [jezzmemo/JJException#33]
对于开启kvo异常处理时，对于10.x(测试系统版本10.3.3)系统版本存在自己实现kvo 到remove时，会与JJException的dealloc中clearKVOData一起导致多次remove而crash. 测试环境可以在YYText与此框架同时启用时，具有多次键盘关闭情况下复现。

**Comment by jezzmemo** [comment]
这个不是冲突吧，就是在clear出了问题，最好把错误信息贴出来，我好定位和确认

**Comment by acekiller** [comment]
先说操作逻辑，由于YYText框架中包含了一个YYTextKeyboardManager类，在10.3.3系统下，当第二次执行收起键盘时，就会促发。
附上异常日志：
Exception Codes: 0x00000000 at 0x0000000000000000 
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'An instance 0x10a79f5f0 of class UIInputSetHostView was deallocated while key value observers were still registered with it. Current observation info: <NSKeyValueObservationInfo 0x174e3b140> (
<NSKeyValueObservance 0x1748418c0: Observer: 0x174e3b0e0, Key path: frame, Options: <New: NO, Old: NO, Prior: NO> Context: 0x0, Property: 0x170851490>
<NSKeyValueObservance 0x174841920: Observer: 0x174e3b0e0, Key path: center, Options: <New: NO, Old: NO, Prior: NO> Context: 0x0, Property: 0x170851640>
<NSKeyValueObservance 0x174841980: Observer: 0x174e3b0e0, Key path: bounds, Options: <New: NO, Old: NO, Prior: NO> Context: 0x0, Property: 0x170851760>
<NSKeyValueObservance 0x174841a10: Observer: 0x174e3b0e0, Key path: transform, Options: <New: NO, Old: NO, Prior: NO> Context: 0x0, Property: 0x170851880>
)'

**Comment by jezzmemo** [comment]
这个问题，在我的demo已经重现了，今天会修复好
@acekiller

**Comment by jezzmemo** [comment]
请更新到0.1.7
