### ISSUE TITLE
所以在没找到更好的办法，只能Swizzle dealloc方法，先清理kvo数据，再执行origin dealloc，不过这样就有个细节做不到，无法提示那些keyPath忘记清理

### ISSUE THREAD

**Issue by huakucha** [jezzmemo/JJException#35]
这不是一个bug 上面内容为你说明的原话，其实你说的“无法提示那些keyPath忘记清理”是可以在相关函数中提示的
1、清除不存在的key也会闪退：hookRemoveObserver里面checkKVOItemExist里面没有else
2、添加监听后没有清除会导致闪退：clearKVOData的时候其实如果正常的话 set里面应该是没有说句的 有数据说明不正常 不正常就要上报
3、添加重复的key导致闪退：hookAddObserver里面的checkKVOItemExist也是没有else
 
没有恶意啊 我发现 你写代码if都没有else啊  😁😁😁...

**Comment by jezzmemo** [comment]
1. hookRemoveObserver，如果没有数据，我else去做啥呢？
2. set里有数据不能说明有问题，因为开发者可能把remove key 放在dealloc里，因为你的dealloc在他的前面，所以这个也是我很纠结的地方
3. hookAddObserver里面的checkKVOItemExist，如果数据存在，我应该去做啥？

没关系，大家讨论问题

**Comment by huakucha** [comment]
checkKVOItemExist check的目的不只有确定有没有key  你想一下 如果程序员正确的操作 是不是 在dealloc里面check就应该是没有key

**Comment by jezzmemo** [comment]
这样的，我set里记录了，所有的keypath,分为以下几种情况:
* 程序员只添加没有remove 删除，这样set集合里都是忘记删除的
* 程序员在dealloc之前删除了所有或者部分的，这样正常，这样set集合里都是忘记删除的
* 异常情况，程序员在dealloc之后删除kepPath,因为kvc_dealloc我在程序员的前面的，所以我先清除了，再执行开发者的remove keypath,这样就会报一些删除不存在的问题，当然不会闪退，只是误报，因为程序员删除的完整性，我无法知道

我应该表达的清楚了吧，其实问题的关键就是什么时候清除keypath,用dealloc清除keypath，就存在这个问题
