### ISSUE TITLE
加入JJException后开断点总是会卡在一处

### ISSUE THREAD

**Issue by QiJing13** [jezzmemo/JJException#36]
NSObject+KVOCrash.m  - (void)hookRemoveObserver:(NSObject *)observer forKeyPath:(NSString *)keyPath 中的 [self hookRemoveObserver:observer forKeyPath:keyPath]; 这一行。 打开断点后老是会在这里卡住，断点继续后还是一直又回到这个地方（取消断点可以继续完成后续流程），这里没有设置断点的啊。版本是最新的

**Comment by jezzmemo** [comment]
是自己工程？还是JJException的示例工程？

**Comment by QiJing13** [comment]
自己工程。 之前用avoidcrash 没有这种问题。 集成是用pod方式集成的

**Comment by jezzmemo** [comment]
收到，只是debug有这种情况，我来测试下

**Comment by jezzmemo** [comment]
我刚刚测试了下，不会啊，断点只和本地的环境有关系，pod安装的话，只是源码和配置引入的，所以我建议你把环境重启下，再试试。
@QiJing13

**Comment by QiJing13** [comment]
我测试了下，添加了all exceptions就会在那里卡住，而且好像和网络请求有关，其它操作没有进入该断点，网络请求用的afnetworking

**Comment by jezzmemo** [comment]
我还是没试出来，你看看身边的人跟你一样的现象？如果没有就是个案

**Comment by jezzmemo** [comment]
#41 

@HZRZCW

**Comment by jezzmemo** [comment]
#43

**Comment by VVennn** [comment]
您好，我也碰到了这样子问题。确实和网络请求有关 @jezzmemo

**Comment by linushao** [comment]
我也用了最新版遇到这个问题，release也是在crash

**Comment by jezzmemo** [comment]
@linushao 如果是crash，麻烦把callStack发出来
