### ISSUE TITLE
长按图片出现系统保存弹窗，然后单击背景视图，出现crash,应该是移除监听的问题

### ISSUE THREAD

**Issue by Brances** [jezzmemo/JJException#37]
![image](https://user-images.githubusercontent.com/10275640/49265754-67defb00-f48e-11e8-9897-f33b49d130bf.png)

**Comment by Brances** [comment]
系统环境是10.3.3会crash ，12.1没问题

**Comment by jezzmemo** [comment]
长按图片出现系统保存弹窗，这步我咋模拟？

**Comment by jezzmemo** [comment]
我看了下清除的逻辑，只存在一种情况可能的异常，就是宿主先释放了，再释放observer，这时就会发生这种异常

**Comment by jezzmemo** [comment]
@Brances @guoyanchao 
帮忙确认下这个代码能否正常工作，我测试过没问题

**Comment by Brances** [comment]
@jezzmemo 你的库应该没在pod上更新 版本最新还是0.1.8

**Comment by jezzmemo** [comment]
@Brances 更新了，你要执行
```
pod update repo
```
才能发现最新版本

**Comment by Brances** [comment]
@jezzmemo nice  已经解决了  辛苦大佬了！
