### ISSUE TITLE
swift 项目启动崩溃

### ISSUE THREAD

**Issue by andyliuzs** [jezzmemo/JJException#38]
2018-12-03 19:48:41.599523+0800 project[3300:446877] +[NSSet jj_swizzleNSSet]: unrecognized selector sent to class 0x1d6a2d110
2018-12-03 19:48:41.599749+0800 project[3300:446877] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '+[NSSet jj_swizzleNSSet]: unrecognized selector sent to class 0x1d6a2d110'
*** First throw call stack:
(0x19ce6fef8 0x19c03da40 0x19cd8c1fc 0x19ce75810 0x19ce774bc 0x1033d15d8 0x1033d1c2c 0x10033c26c 0x100183254 0x1001833e4 0x1c9db3c68 0x1c9db53d0 0x1c9dbae1c 0x1c965bc18 0x1c96646f0 0x1c965b894 0x1c965c234 0x1c965a334 0x1c9659fe0 0x1c965f1a0 0x1c9660100 0x1c965f058 0x1c9663d9c 0x1c9db9314 0x1c99a4c34 0x19f89f890 0x19f8aa658 0x19f8a9d50 0x104ed8de4 0x104edca2c 0x19f8de640 0x19f8de2cc 0x19f8de8e8 0x19cdfe5b8 0x19cdfe538 0x19cdfde1c 0x19cdf8ce8 0x19cdf85b8 0x19f06c584 0x1c9dbcbc8 0x100184ca8 0x19c8b8b94)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by jezzmemo** [comment]
请问是如何引入工程的，pod引入好像没有遇到过，请问是不是源码引入？

**Comment by andyliuzs** [comment]
我用的carthage

**Comment by jezzmemo** [comment]
不好意思，我刚刚确认过了，用carthage的话，确实有问题，我没有吧最新的代码加进来，我尽快更新

**Comment by jezzmemo** [comment]
麻烦升级到0.1.9，问题已经解决了
@andyliuzs

**Comment by ITLMXMF222** [comment]
初始化 报 Unrecognized selector -[Kingfisher.ImageCache jj_deallocBlock:]
