### ISSUE TITLE
我下载demo，运行demo，然后还是奔溃了

### ISSUE THREAD

**Issue by iosApem** [jezzmemo/JJException#4]
- Device: [iphonex模拟器]
 - OS: [iOS11]
我下载demo，运行demo，点击push contronller，
最后还是奔溃了，不明白保护的效果指的是什么

**Comment by jezzmemo** [comment]
默认是显示抛出错误的。

1.如果你不想把错误显示抛出来，可以将run 的schema调整成非debug模式
2.还有一个办法就是注释JJExceptionProxy的NSAssert(NO, @"");这行代码

@iosApem

**Comment by jezzmemo** [comment]
> 不明白保护的效果指的是什么
注意看文档，数组越界，key-value的value为nil,方法找不到，这类常见crash，引入后将不会闪退

**Comment by iosApem** [comment]
谢谢
