### ISSUE TITLE
AVFoundation使用有问题

### ISSUE THREAD

**Issue by msh940620** [jezzmemo/JJException#40]
开启JJExceptionGuardKVOCrash后，AVFoundation加载本地视频资源偶现只有声音没有视频的异常，关闭则正常，设备版本iOS11 iOS12 都可以复现，视频格式mp4，编码264，目前只有加载本地视频有这个问题。播放的逻辑是检查到AVPlayerItem.status == AVPlayerItemStatusReadyToPlay 则开始播放。

**Comment by jezzmemo** [comment]
复现的步骤就是:
用AVFoundation来播放MP4文件，这个问题马上出来了？

**Comment by jezzmemo** [comment]
我刚刚用以下的简单的代码测试，没有问题啊:
`
@interface PlayerViewController ()

@property (nonatomic,readwrite,strong)AVPlayerItem* item;

@property (nonatomic,readwrite,strong)AVPlayer* player;

@end

@implementation PlayerViewController

- (void)viewDidLoad {
    [super viewDidLoad];
    NSURL *url = [[NSBundle mainBundle]URLForResource:@"test" withExtension:@"mp4"];
    AVAsset* set = [AVAsset assetWithURL:url];
    self.item = [[AVPlayerItem alloc]initWithAsset:set];
    self.player = [AVPlayer playerWithPlayerItem:self.item];
    AVPlayerLayer* layer = [AVPlayerLayer playerLayerWithPlayer:self.player];
    layer.frame = CGRectMake(0, 0, self.view.frame.size.width, 600);
    [self.view.layer addSublayer:layer];
    
    [self.item addObserver:self forKeyPath:@"status" options:0 context:nil];
}

- (void)observeValueForKeyPath:(NSString *)keyPath
                      ofObject:(id)object
                        change:(NSDictionary *)change
                       context:(void *)context {
    
        dispatch_async(dispatch_get_main_queue(), ^{
            [self.item removeObserver:self forKeyPath:@"status"];
            NSLog(@"self.item.status=%ld",(long)self.item.status);
            if (self.item.status == AVPlayerItemStatusReadyToPlay) {
                [self.player play];
            } else {
                
            }
        });
}
@end
`
