### ISSUE TITLE
与FBKVOController一起用的话有问题

### ISSUE THREAD

**Issue by saberChen** [jezzmemo/JJException#41]
总是断点在NSObject+KVOCrash.m P297行，是抓取到crash信息了吗，
[self hookRemoveObserver:observer forKeyPath:keyPath];

有时会断在方法cleanKVOData中的@try中，不知道是否因为同FBKVOController一起使用导致的，麻烦告知一下，谢谢

**Comment by jezzmemo** [comment]
只是引入FBKVOController了，有没简单的测试代码，而且能出现断点的情况

**Comment by jezzmemo** [comment]
我想到一点，就是Xcode 有一个All Exception的断点，当系统抛出Exception时，这个断点都会接收，所以你要检查下，你是否Enable这个开关，如果不希望就直接关掉

**Comment by jezzmemo** [comment]
#43

**Comment by saberChen** [comment]
你好，没有闪退，关闭断点也运行的，可能是All Exception断点造成的，但是进帖子详情页，数据无法加载，未引入时是正常加载，很奇怪，目前没测试代码，都是直接在工程里调试的，我再试试看，谢谢你！
