### ISSUE TITLE
与AFN配合kvo启动闪退

### ISSUE THREAD

**Issue by dqb101140127** [jezzmemo/JJException#43]
**Describe the bug**

**To Reproduce**

**Please complete the following information**
<img width="760" alt="image" src="https://user-images.githubusercontent.com/13044675/49844930-add97e80-fdff-11e8-844f-618e1aac05f5.png">
<img width="378" alt="image" src="https://user-images.githubusercontent.com/13044675/49844968-cb0e4d00-fdff-11e8-9da0-8252c0b8af77.png">
<img width="1096" alt="image" src="https://user-images.githubusercontent.com/13044675/49845008-e1b4a400-fdff-11e8-9c8e-f29f1570cd09.png">
<img width="1063" alt="image" src="https://user-images.githubusercontent.com/13044675/49845027-f6913780-fdff-11e8-84b6-571b6c039235.png">

**Comment by dqb101140127** [comment]
> 如果关闭断点，还有这个问题不？

去掉断点时没问题的  点击继续是不行的

**Comment by jezzmemo** [comment]
这个问题还是跟断点有关系，因为系统抛了一个Exception出来了，而且你本地的Xcode打开了AllException开关，本地就自动停留在抛出的地方，这个原因就是防止忘记删除KVO导致的，因为我不确认使用KVO的人，是否记得删除，所以我在dealloc之前删除了，但是有些开发者是删除的，所以导致重复删除，导致有异常抛出，但是不影响App的正常运行，只是有点影响断点
