### ISSUE TITLE
循环调用问题

### ISSUE THREAD

**Issue by guoyanchao** [jezzmemo/JJException#44]
(void) hookAddObject:(id)object {
if (object) {
[self hookAddObject:object];
} else {
handleCrashException(JJExceptionGuardArrayContainer,@"NSSet addObject nil object");
}
}这个方法会造成循环调用吗？

**Comment by jezzmemo** [comment]
不会，你去了解下objective-c的swizzle机制，hookaddobject指向原始方法，所以不会循环

**Comment by guoyanchao** [comment]
我刚才测试了下，到现在还在循环调用那，跑了好久了

**Comment by jezzmemo** [comment]
你怎么测试的？demo给我看看

**Comment by guoyanchao** [comment]
NSMutableArray *set = [NSMutableArray array];
    [set addObject:nil];

**Comment by jezzmemo** [comment]
说下你的JJException的版本，你有没特殊的一些三方库，最后贴下你的初始化代码详细点给我看看
