### ISSUE TITLE
集成在项目里之后好像和FMDB有冲突，造成了无限循环调用

### ISSUE THREAD

**Issue by carlchou00** [jezzmemo/JJException#45]
主要是字符串的那几个方法：
hookStringWithUTF8String: NSString(StringHook)；

hookRangeOfString:options:range:locale: NSString(StringHook)；

hookSubstringFromIndex: NSMutableString(MutableStringHook)

hookSubstringToIndex: NSMutableString(MutableStringHook)

hookSubstringWithRange: NSString(StringHook)

**Comment by jezzmemo** [comment]
麻烦把你的测试代码，发出来下，我好测试

**Comment by carlchou00** [comment]
> 麻烦把你的测试代码，发出来下，我好测试
我是集成在项目里，然后线上环境捕捉到的日志，没有测试代码，不好复现

**Comment by jezzmemo** [comment]
那麻烦把调用栈麻烦发出来看看，这样也可以帮我排查问题

**Comment by carlchou00** [comment]
![screen shot 2018-12-27 at 16 33 24](https://user-images.githubusercontent.com/13175918/50472841-6c4af500-09f5-11e9-97ba-98d57eb911cf.png)

**Comment by carlchou00** [comment]
![screen shot 2018-12-27 at 16 36 07](https://user-images.githubusercontent.com/13175918/50472854-871d6980-09f5-11e9-9e7a-e230e7b94b84.png)

**Comment by carlchou00** [comment]
<img width="1240" alt="screen shot 2018-12-27 at 16 40 13" src="https://user-images.githubusercontent.com/13175918/50472962-188cdb80-09f6-11e9-91e0-df11769ff6f2.png">

**Comment by jezzmemo** [comment]
```
 NSString *path = [NSTemporaryDirectory() stringByAppendingPathComponent:@"tmp.db"];
    FMDatabase *db = [FMDatabase databaseWithPath:path];
    
    if (![db open]) {
    }
    
    
    NSString *sql = @"create table bulktest1 (id integer primary key autoincrement, x text);"
    "create table bulktest2 (id integer primary key autoincrement, y text);"
    "create table bulktest3 (id integer primary key autoincrement, z text);"
    "insert into bulktest1 (x) values ('XXX');"
    "insert into bulktest2 (y) values ('YYY');"
    "insert into bulktest3 (z) values ('ZZZ');";
    
    [db executeStatements:sql];
    
    FMResultSet *s = [db executeQuery:@"SELECT x FROM bulktest1"];
    if ([s next]) {
        NSString* result = [s stringForColumnIndex:0];
    }
```
我用以上代码简单测试了下，没问题啊，我不知道你们是什么场景，把你们初始化JJException的代码和地方给我看下

**Comment by jezzmemo** [comment]
这样的，我这里简单的场景无法重现，如果你有时间，可以弄一个干净的工程试试，然后简单的贴下过程或者代码片段，都可以

**Comment by ITLMXMF222** [comment]
你好 我这边初始化 就崩了，报的Unrecognized selector -[Kingfisher.ImageCache jj_deallocBlock:]错误
