### ISSUE TITLE
jj_deallocBlock

### ISSUE THREAD

**Issue by ITLMXMF222** [jezzmemo/JJException#47]
**Describe the bug**

**To Reproduce**

**Please complete the following information**

**Comment by jezzmemo** [comment]
说下JJException的版本，以及你的环境和初始化代码

**Comment by ITLMXMF222** [comment]
1:初始化代码
       JJException.configExceptionCategory(.allExceptZombie)
        JJException.startGuard()
        JJException.register(self);
   2:环境是  xode10.1 iOS11.1  
   3：我是pod install JJException  但是pod search JJException 查看版本失败 报：[!] Unable to find a pod with name, author, summary, or description matching `JJException`

**Comment by jezzmemo** [comment]
你查看下你的本地的Podfile.lock文件

**Comment by ITLMXMF222** [comment]
我的JJException版本是 0.1.9

**Comment by ITLMXMF222** [comment]
你好！ 请问是什么问题嘛？

**Comment by jezzmemo** [comment]
我稍后确认下，尽快给你答复

**Comment by ITLMXMF222** [comment]
好的。谢谢你。

**Comment by jezzmemo** [comment]
我用纯Swift工程，用Pod引入:
```
target 'TestPureSwift' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'JJException'

end
```

初始化代码:
```
    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
        self.registerJJException()
        return true
    }
    
    func registerJJException(){
        JJException.configExceptionCategory(.allExceptZombie)
        JJException.startGuard()
        JJException.register(self);
    }
```
没有问题，我不知道和你的有什么区别？

**Comment by ITLMXMF222** [comment]
代码写的跟你一样  我这边自己看了。跟这个有关系pod 'Alamofire', '~> 4.7' #网络请求  我一旦打开网络请求数据话就会报上面的错误。如果关闭网络请求 就不会了。。

**Comment by ITLMXMF222** [comment]
我当前项目是游客模式。

**Comment by ITLMXMF222** [comment]
我在细看下  对网络请求数据之后 对某个控件赋值 会崩  
 if self.personInfoModel.avatarUrl != nil {
                     self.headImg.kf.setImage(with: URL(string:self.personInfoModel.avatarUrl!))
                }
上面这就代码是 网络请求成功后给headImg(UIImageView)控件赋值  就崩了。如果不执行就不会蹦

**Comment by jezzmemo** [comment]
所以你还引入了Kingfisher，如果你确认，我稍后测试下，谢谢

**Comment by ITLMXMF222** [comment]
Alamofire.request("https://httpbin.org/get").responseJSON { response in
            print("Request: \(String(describing: response.request))")   // original url request
            print("Response: \(String(describing: response.response))") // http url response
            print("Result: \(response.result)")                         // response serialization result

            if let json = response.result.value {
                print("JSON: \(json)") // serialized json response
                self.headImg.kf.setImage(with: URL(string:"https://pub-obs-2f82.obs.cn-north-1.myhwclouds.com/1546932896565.jpg"))
            }

            if let data = response.data, let utf8Text = String(data: data, encoding: .utf8) {
                print("Data: \(utf8Text)") // original server data as UTF8 string
            }
        }
        
对啊 上面的家了   self.headImg.kf.setImage(with: URL(string:"https://pub-obs-2f82.obs.cn-north-1.myhwclouds.com/1546932896565.jpg")) 就崩了

**Comment by ITLMXMF222** [comment]
我用你写的  网络请求数据  加了这个 self.headImg.kf.setImage(with: URL(string:"https://pub-obs-2f82.obs.cn-north-1.myhwclouds.com/1546932896565.jpg")) 就崩了

**Comment by jezzmemo** [comment]
我重现了，谢谢，我尽快解决掉

**Comment by ITLMXMF222** [comment]
好的。麻烦你了。

**Comment by jezzmemo** [comment]
> 我发现一个问题 我写了个测试
> let dit : NSDictionary = ["key":"varlye"]
> print(dit["key111"] as! String)
> 它不会保护app，app直接蹦了 oc就可以

这种保护是基于runtime,swift很多没有runtime机制，所以swift很多保护不了，JJException主要还是针对Objective-c的

**Comment by jezzmemo** [comment]
> 你好。如果好了跟我说下。这边项目后台就要上线了。目前有个bug问题需要借助你这个来查找下。。谢谢了

晚点好了，我会给你留言的

**Comment by jezzmemo** [comment]
问题已经解决了，原因是Kingfisher里的通知用的纯Swift对象，导致是不能用Category这种方法，所以没有找到方法
