### ISSUE TITLE
__jj_swizzleDeallocIfNeeded_block_invoke_3  ，导致程序崩溃，今天升级了最新的版本，pod后

### ISSUE THREAD

**Issue by TYQbag** [jezzmemo/JJException#48]
**Describe the bug**

**To Reproduce**

**Please complete the following information**

**Comment by TYQbag** [comment]
Cannot remove an observer <AVKVODispatcher 0x282f44140> for the key path "currentItem" from <AVPlayer 0x282f44840> because it is not registered as an observer，播放视频，崩溃

**Comment by jezzmemo** [comment]
JJException是0.1.9版本？

**Comment by TYQbag** [comment]
目前已经发现好几个KVO 导致的Crash,视频播放代码：
 //初始化
    self.playerView = [[AVPlayerViewController alloc]init];
    //通过AVPlayerItem创建AVPlayer
    self.player = [[AVPlayer alloc] initWithURL:url];
    //设置AVPlayerViewController内部的AVPlayer为刚创建的AVPlayer
    self.playerView.player = self.player;
    [self.playerView.view setFrame:self.view.bounds];
    [self.view addSubview:self.playerView.view];
    [self.playerView.player play];

**Comment by TYQbag** [comment]
现在已经把KVO关掉了

**Comment by TYQbag** [comment]
我是在12.0的系统上，播放的是本地视频

**Comment by jezzmemo** [comment]
我刚刚用12.1的真机，测试过了，也没有问题，你的环境是不是有第三方依赖？如果方便最好能找出什么情况下才会出问题
