### ISSUE TITLE
能处理Signal类型的崩溃吗

### ISSUE THREAD

**Issue by guanzhendong** [jezzmemo/JJException#50]
如果能处理，能定位崩溃位置吗

**Comment by jezzmemo** [comment]
JJException是利用Runtime机制保护App的，不是定位错误的，Signal的奔溃只能捕捉，不能彻底拦截，如果想知道App的闪退信息,可能Bugly更适合你

**Comment by jezzmemo** [comment]
JJException是有记录CallStack的，还有当前的堆栈地址，需要配合符号表才能找到具体的地方，当然如果bugly来配合，就不需要手动根据地址来查询具体的代码，因为我的错误信息上传到了Bugly类似的工具来管理，我们除了少数闪退没有信息，大部分提示的还是比较清楚的，如果提示不清楚的，可以多方面来排查这个问题，比如在什么场景，什么页面，缩减排查范围.

**Comment by guanzhendong** [comment]
<img width="1269" alt="2019-01-22 5 22 03" src="https://user-images.githubusercontent.com/13097498/51527951-94047000-1e70-11e9-9789-b8ef95f26f41.png">
<img width="1279" alt="2019-01-22 6 09 06" src="https://user-images.githubusercontent.com/13097498/51528090-daf26580-1e70-11e9-9d3d-7c55db3390db.png">
我们项目崩溃量前二的是这种，是启动崩溃，但是看不出是哪里

**Comment by jezzmemo** [comment]
这个不是很明显是跟ECLIte有关，看样子是内存操作有问题，具体情况你要具体分析
