### ISSUE TITLE
使用这个组件引起的性能问题咋解决

### ISSUE THREAD

**Issue by SQsteven** [jezzmemo/JJException#51]

**Comment by jezzmemo** [comment]
怎么判定是这个组件引起的性能问题？

**Comment by SQsteven** [comment]
我项目中有个页面，有一些的数组的操作，这些操作是在viewDidLoad中执行的，引入这个组件后，在一些比较老的机型上（新机上的影响时比较小的），push到这个界面的流畅度明显下降，于是用time profiler 做一下耗时测试，代码定位到NS（Muatble）Array（Hook） 与NS（Mutable）AttributedString 有一定的耗时，当然，也可能是其他地方的问题引起的，由于时间原因，我也没有对这个组件做其他的测试对比，有空后会专门研究一下的

**Comment by jezzmemo** [comment]
嗯，麻烦仔细对比下，我之前做过性能测试，集合类的hook，影响极小，所以希望给出具体的例子和场景
