### ISSUE TITLE
使用和这个库的时候会崩溃在这一行

### ISSUE THREAD

**Issue by ChinaChailu** [jezzmemo/JJException#52]
**Describe the bug**

**To Reproduce**

**Please complete the following information**
void jj_swizzleDeallocIfNeeded(Class class)
{
    static SEL deallocSEL = NULL;
    static SEL cleanupSEL = NULL;
    
    static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^{
        deallocSEL = sel_getUid("dealloc");
        cleanupSEL = sel_getUid("jj_cleanKVO");
    });
    
    @synchronized (class) {
        if ( !jj_requiresDeallocSwizzle(class) ) {
            return;
        }
        
        objc_setAssociatedObject(class, &jjSwizzledDeallocKey, @(YES), OBJC_ASSOCIATION_RETAIN_NONATOMIC);
    }
    
    Method dealloc = class_getInstanceMethod(class, deallocSEL);
    
    if ( dealloc == NULL ) {
        Class superclass = class_getSuperclass(class);
        
        class_addMethod(class, deallocSEL, imp_implementationWithBlock(^(__unsafe_unretained id self) {
            
            ((void(*)(id, SEL))objc_msgSend)(self, cleanupSEL);
            
            struct objc_super superStruct = (struct objc_super){ self, superclass };
            ((void (*)(struct objc_super*, SEL))objc_msgSendSuper)(&superStruct, deallocSEL);
            
        }), method_getTypeEncoding(dealloc));
    }else{
        __block IMP deallocIMP = method_setImplementation(dealloc, imp_implementationWithBlock(^(__unsafe_unretained id self) {
            ((void(*)(id, SEL))objc_msgSend)(self, cleanupSEL);
            
            ((void(*)(id, SEL))deallocIMP)(self, deallocSEL); //断点停留在这行代码上
        }));
    }
}

**Comment by jezzmemo** [comment]
是断点停留了，还是闪退了？关掉断点是不是没事？

**Comment by ChinaChailu** [comment]
闪退了

**Comment by ChinaChailu** [comment]
刚启动就崩溃了 ，但是这个页面还没有创建 deallocSEL 是个二级页面

**Comment by ChinaChailu** [comment]
deallocSEL的类里重写了这个 dealloc 方法

**Comment by ChinaChailu** [comment]
关闭断点后 直接运行就不会崩溃

**Comment by ChinaChailu** [comment]
删除页面里的 dealloc 方法也不会崩溃

**Comment by jezzmemo** [comment]
你开了全局断点的问题，断点这个问题，我后续优化
