### ISSUE TITLE
真机切换开启/关闭防护时会造成闪退

### ISSUE THREAD

**Issue by Ericfengshi** [jezzmemo/JJException#54]
在Demo程序中快速切换 开启/关闭 防护时会造成闪退，100%重现

相关信息：
 - Device: iPhone 7 Plus
 - OS: iOS 12.1.2
 - Version master(2019.2.18)

![image](https://user-images.githubusercontent.com/9972101/52925866-33345e80-336e-11e9-9de0-432b2a6fb350.png)
![image](https://user-images.githubusercontent.com/9972101/52925899-5fe87600-336e-11e9-8833-6c12b7ec8484.png)
会在方法 -[NSObject(ZombieHook) hookDealloc] 中死循环

**Comment by jezzmemo** [comment]
确实有这个问题，我分析下这个问题是由于dealloc被hook后，然后再来取消hook,
反复操作后，有一种临界状态，就是取消了hook,origin指向了当前的method，导致死循环。

目前解决方案只有一种：就是在dealloc里有锁，但是这种会导致dealloc的效率降低，所以我看看有没跟更好的方案来处理

**Comment by sp55** [comment]
> 确实有这个问题，我分析下这个问题是由于dealloc被hook后，然后再来取消hook,
> 反复操作后，有一种临界状态，就是取消了hook,origin指向了当前的方法的指针，导致死循环。
> 
> 目前解决方案只有一种：就是在dealloc里有锁，但是这种会导致dealloc的效率降低，所以我看看有没跟更好的方案来处理

为什么要做实时关闭保护的操作  这个耗费内存吗还是什么原因

**Comment by jezzmemo** [comment]
做实时关闭，只是为了方便开关，方式没有考虑这么多，如果取消关闭就不会有这个问题

**Comment by jezzmemo** [comment]
我慎重考虑了下，主要是以下考虑:
1.会对整体性能有影响
2.实时关闭的实用性不高，App启动开启即可

所以我的方案是放弃实时关闭这个功能.
