### ISSUE TITLE
求问一个事情，比如NSArray hook的是__NSArray 等一些私有类

### ISSUE THREAD

**Issue by dollarfromchina** [jezzmemo/JJException#56]
求问一个事情，比如NSArray hook的是__NSArray 等一些私有类，为什么要hook私有类而不是hook NSArray呢？

**Comment by dollarfromchina** [comment]
是因为hook私有类覆盖面更广吗

**Comment by jezzmemo** [comment]
不是，ios有类族的概念，对外api和实际实现的具体类名是不一样的，所以在hook的时候，要hook到实际的类，所以有这些你没见过的类名
