### ISSUE TITLE
求问一个事情，使用以后偶现了如下的两个死循环崩溃，这个是什么原因呢，使用的最新版本的代码

### ISSUE THREAD

**Issue by dollarfromchina** [jezzmemo/JJException#57]
![xnip2019-03-03_14-59-20](https://user-images.githubusercontent.com/3004652/53692178-064c6680-3dc6-11e9-8475-8d7d2398b92a.jpg)
![xnip2019-03-03_15-06-50](https://user-images.githubusercontent.com/3004652/53692179-06e4fd00-3dc6-11e9-88df-abea2b46560d.jpg)

**Comment by jezzmemo** [comment]
初始化的代码，在didFinishLaunchingWithOptions第一行不？

**Comment by dollarfromchina** [comment]
不是

**Comment by jezzmemo** [comment]
麻烦看看我的使用介绍，加粗部分已经写过了，原因就是在替换的过程中，有其他线程正在操作导致的，所以是偶尔不一定每次都会

**Comment by dollarfromchina** [comment]
好的 多谢
