### ISSUE TITLE
NSUserDefaults - (void)setObject:(nullable id)value forKey:(NSString *)defaultName Crash

### ISSUE THREAD

**Issue by superClown** [jezzmemo/JJException#58]
NSUserDefaults will cause a crash when the NSDictionary contains a null value
For example
NSDictionary *dict = @{@"key": [NSNull null]};// may "null"
[[NSUserDefaults standardUserDefaults] setObject:dict forKey:@"key"]
Can you help me with a process?

**Comment by Liuqiang96** [comment]
((void(*)(id, SEL))deallocIMP)(self, deallocSEL);在启动时候回崩溃到这里

**Comment by jezzmemo** [comment]
> ```
>         ((void(*)(id, SEL))deallocIMP)(self, deallocSEL);在启动时候回崩溃到这里
> ```

有没详细点的错误信息？

**Comment by Liuqiang96** [comment]
> > ```
> >         ((void(*)(id, SEL))deallocIMP)(self, deallocSEL);在启动时候回崩溃到这里
> > ```
> 
> 有没详细点的错误信息？

不是必现的BUG，我这边下次把堆栈信息给贴过来

**Comment by jezzmemo** [comment]
> NSUserDefaults will cause a crash when the NSDictionary contains a null value
> For example
> NSDictionary *dict = @{@"key": [NSNull null]};// may "null"
> [[NSUserDefaults standardUserDefaults] setObject:dict forKey:@"key"]
> Can you help me with a process?

NSUserDefaults issue will be added to JJException in plans
