### ISSUE TITLE
 NSMutableDictionary和NSMutableArray崩溃

### ISSUE THREAD

**Issue by chendaming** [jezzmemo/JJException#63]
NSMutableDictionary *dict = @{
                                  @"name" : @"text"
                                  
                                  }.mutableCopy;
    NSString *ageKey = nil;
    dict[ageKey] = @(25);
    NSLog(@"%@",dict);

NSMutableArray *array = @[@"text"].mutableCopy;
    array[3] = @"iOS";

这样会导致崩溃

**Comment by jezzmemo** [comment]
经过测试，确实会，需要新增两个hook
```
__NSDictionaryM setObject:forKeyedSubscript:
__NSArrayM setObject:atIndexedSubscript:
```
