### ISSUE TITLE
ios 使用这个库崩溃

### ISSUE THREAD

**Issue by fangbo111** [jezzmemo/JJException#64]
void jj_swizzleDeallocIfNeeded(Class class)
{
    static SEL deallocSEL = NULL;
    static SEL cleanupSEL = NULL;
    
    static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^{
        deallocSEL = sel_getUid("dealloc");
        cleanupSEL = sel_getUid("jj_cleanKVO");
    });
    
    @synchronized (class) {
        if ( !jj_requiresDeallocSwizzle(class) ) {
            return;
        }
        
        objc_setAssociatedObject(class, &jjSwizzledDeallocKey, @(YES), OBJC_ASSOCIATION_RETAIN_NONATOMIC);
    }
    
    Method dealloc = class_getInstanceMethod(class, deallocSEL);
    
    if ( dealloc == NULL ) {
        Class superclass = class_getSuperclass(class);
        
        class_addMethod(class, deallocSEL, imp_implementationWithBlock(^(__unsafe_unretained id self) {
            
            ((void(*)(id, SEL))objc_msgSend)(self, cleanupSEL);
            
            struct objc_super superStruct = (struct objc_super){ self, superclass };
            ((void (*)(struct objc_super*, SEL))objc_msgSendSuper)(&superStruct, deallocSEL);
            
        }), method_getTypeEncoding(dealloc));
    }else{
        __block IMP deallocIMP = method_setImplementation(dealloc, imp_implementationWithBlock(^(__unsafe_unretained id self) {
            ((void(*)(id, SEL))objc_msgSend)(self, cleanupSEL);
            
            ((void(*)(id, SEL))deallocIMP)(self, deallocSEL);
        }));
    }
}

崩溃在  ((void(*)(id, SEL))deallocIMP)(self, deallocSEL);这一行  我网上又看到类似问题 你的答案是 全局断电的问题   但是 我这边把断点全部移除还是会崩溃  
![屏幕快照 2019-04-18 下午3 00 52](https://user-images.githubusercontent.com/16485276/56342510-c8c36180-61ea-11e9-8675-95d61885952e.png)

**Comment by jezzmemo** [comment]
这个不是全局断点的问题，能否重现这个问题？

**Comment by fangbo111** [comment]
这个是偶现的问题  但是 几率还是挺大的  应该能重现  我这边用的是0.2.1版本

**Comment by jezzmemo** [comment]
收到，我尽快review code，看看能否稳定重现

**Comment by fangbo111** [comment]
需要我这边配合吗   应为 我在用你的这个库  这几天 又要上线了

**Comment by jezzmemo** [comment]
在监控类型里不要配置JJExceptionGuardKVOCrash就可以了，我解决里了，会这里发通知的

**Comment by fangbo111** [comment]
![屏幕快照 2019-04-18 下午3 46 33](https://user-images.githubusercontent.com/16485276/56344939-2fe41480-61f1-11e9-83e1-e004036832dc.png)
这样配置就行了吗

**Comment by jezzmemo** [comment]
```
JJExceptionGuardNone
JJExceptionGuardAllExceptZombie
```
这两个不要就行了

**Comment by fangbo111** [comment]
好的  谢谢
