### ISSUE TITLE
请教一下，这个库与@try catch有冲突吗？

### ISSUE THREAD

**Issue by Sunxb** [jezzmemo/JJException#65]

**Comment by Sunxb** [comment]
JJException.exceptionWhenTerminate = NO;的时候，用到@try catch的地方会crash，然后跟timer定时器有关的地方也会crash。

**Comment by jezzmemo** [comment]
JJException.exceptionWhenTerminate跟crash没有关系吧，能否把日志发出来，我来分析下

**Comment by Sunxb** [comment]
@jezzmemo 

2019-04-29 10:33:24.233173+0800 fmb[7789:2070185] ================================JJException Start==================================
2019-04-29 10:33:24.233315+0800 fmb[7789:2070185] JJException Type:8
2019-04-29 10:33:24.233383+0800 fmb[7789:2070185] JJException Description:NSMutableArray objectAtIndex invalid index:0 total:0
2019-04-29 10:33:24.233503+0800 fmb[7789:2070185] JJException Extra info:(null)
2019-04-29 10:33:24.234437+0800 fmb[7789:2070185] JJException CallStack:(
	0   fmb                                 0x00000001019227f4 -[JJExceptionProxy handleCrashException:exceptionCategory:extraInfo:] + 144
	1   fmb                                 0x0000000101922370 _Z20handleCrashException24JJExceptionGuardCategoryP8NSString + 120
	2   fmb                                 0x000000010192501c -[NSMutableArray(MutableArrayHook) hookObjectAtIndex:] + 224
	3   fmb                                 0x0000000100d6284c -[LTShareNewsCell dequeueReusableImageView:] + 104
	4   fmb                                 0x0000000100d64140 -[LTShareNewsCell setModel:] + 1600
	5   fmb                                 0x00000001010b6a80 +[QKCellModel setUpCellData:cell:indexPath:] + 488
	6   fmb                                 0x00000001010b60dc __58+[QKCellModel tableViewForCellHeight:cellModel:indexPath:]_block_invoke + 120
	7   fmb                                 0x00000001015431f4 -[UITableView(FDTemplateLayoutCell) fd_heightForCellWithIdentifier:configuration:] + 200
	8   fmb                                 0x00000001010b5e10 +[QKCellModel tableViewForCellHeight:cellModel:indexPath:] + 980
	9   fmb                                 0x00000001013bdb04 -[QKBaseTableController tableView:heightForRowAtIndexPath:] + 404
	10  UIKit                               0x000000018f0de728 <redacted> + 112
	11  UIKit                               0x000000018eea1a24 <redacted> + 316
	12  UIKit                               0x000000018ee64f7c <redacted> + 2488
	13  UIKit                               0x000000018ee67120 <redacted> + 108
	14  UIKit                               0x000000018ee6706c <redacted> + 152
	15  UIKit                               0x000000018ee66a88 <redacted> + 1512
	16  fmb                                 0x000000010127c0f4 __64-[UITableView(FDIndexPathHeightCacheInvalidation) fd_reloadData]_block_invoke_2 + 48
	17  fmb                                 0x000000010127bc9c __FD_TEMPLATE_LAYOUT_CELL_PRIMARY_CALL_IF_CRASH_NOT_OUR_BUG__ + 56
	18  fmb                                 0x000000010127c040 -[UITableView(FDIndexPathHeightCacheInvalidation) fd_reloadData] + 272
	19  fmb                                 0x000000010196f1c8 -[UITableView(MJRefresh) mj_reloadData] + 40
	20  fmb                                 0x00000001013fc094 __36-[LTTicketDetailController loadData]_block_invoke + 1540
	21  fmb                                 0x0000000101426e1c __36-[LTTicketDetailModel loadCellModel]_block_invoke + 600
	22  libdispatch.dylib                   0x00000001089e52cc _dispatch_call_block_and_release + 24
	23  libdispatch.dylib                   0x00000001089e528c _dispatch_client_callout + 16
	24  libdispatch.dylib                   0x00000001089e9ea0 _dispatch_main_queue_callback_4CF + 1196
	25  CoreFoundation                      0x000000018578a544 <redacted> + 12
	26  CoreFoundation                      0x0000000185788120 <redacted> + 2012
	27  CoreFoundation                      0x00000001856a7e58 CFRunLoopRunSpecific + 436
	28  GraphicsServices                    0x0000000187554f84 GSEventRunModal + 100
	29  UIKit                               0x000000018edfc67c UIApplicationMain + 236
	30  fmb                                 0x0000000100f9ab68 main + 124
	31  libdyld.dylib                       0x00000001851c456c <redacted> + 4
)
2019-04-29 10:33:24.235438+0800 fmb[7789:2070185] ================================JJException End====================================


里面这句[LTShareNewsCell dequeueReusableImageView:]  是包裹在一个@try里面的  如果取不到view  在catch里面会new一个  但是报错了 ~

**Comment by jezzmemo** [comment]
从日志分来说，数组越界的异常，而且是抛出来了，我不知道你的catch里具体做了什么，这个错误不是闪退了，只是被JJException拦截到了，不会导致闪退的。

**Comment by Sunxb** [comment]
JJException.exceptionWhenTerminate = NO; 应该是不闪退 但是确实闪退了。。没有什么特别的代码。
@jezzmemo

**Comment by jezzmemo** [comment]
@Sunxb 有没重现的步骤或者demo的示例，这样我比较方便重现问题，快速定位问题

**Comment by Sunxb** [comment]
@jezzmemo 

你好，抱歉这么久了才回复。我重新写了一个小例子 ，现在不是crash的问题。

`    NSMutableArray * arr = @[@"0",@"1"].mutableCopy;
    NSString * str = @"";
    
    @try {
        str = [arr objectAtIndex:2];
    } @catch (NSException *exception) {
        [arr addObject:@"2"];
        str = [arr objectAtIndex:2];
    } @finally {
        NSLog(@"--==--%@--==--",str);
    }
    
    NSLog(@"end");`

这种带有try catch的是不是不太兼容，其实这里的try catch已经处理好越界的问题了，打印str应该是2，但是这里try里面的越界被捕获到了，打印的时候输出了null。

**Comment by jezzmemo** [comment]
如果从这个角度来说，JJException捕捉到的异常不会触发Exception，因为这些异常被JJException提前规避了，所以如果加了JJException的话，有些异常是捕捉不到的
