### ISSUE TITLE
对`- (void)setObject:(ObjectType)obj atIndexedSubscript:(NSUInteger)idx`的hook实现有点问题

### ISSUE THREAD

**Issue by xq-120** [jezzmemo/JJException#66]
这个方法只要idx不超出总长度,就不会崩溃.
但是这里判断只能index<self.count.会导致没法正常使用.
- (void) hookSetObject:(id)object atIndexedSubscript:(NSUInteger)index {
    if (index < self.count && object) {
        [self hookSetObject:object atIndexedSubscript:index];
    }else{
        handleCrashException(JJExceptionGuardArrayContainer,[NSString stringWithFormat:@"NSMutableArray setObject invalid object:%@ atIndexedSubscript:%tu total:%tu",object,index,self.count]);
    }
}

**Comment by jezzmemo** [comment]
我刚刚去检查了下，这个验证没问题啊，这个API的目的就是在有效范围内的下标，设置有效的值，否则都是非法的

**Comment by xq-120** [comment]
你好,测试代码如下
NSMutableArray *arr = [NSMutableArray array];
[arr setObject:@"0" atIndexedSubscript:0];
NSLog(@"%@", arr); 
这里会打印 0,不会崩溃.也就是setObject:atIndexedSubscript:方法,idx是可以等于self.count的.
你那里是判断index<self.count,因此就走else了.不知道有没有表述清楚

**Comment by jezzmemo** [comment]
明白了，这样说确实有问题，我尽快修复，马上更新

**Comment by xq-120** [comment]
👍
