### ISSUE TITLE
急，bug

### ISSUE THREAD

**Issue by wscqs** [jezzmemo/JJException#67]
NSURL *requestURL = [NSURL URLWithString:@"https://itunes.apple.com/lookup?country=cn&bundleId=com.mbalib.ios.wiki&timestamp=1559269796"];
    NSURLRequest *request = [NSURLRequest requestWithURL:requestURL];
    NSURLSession *session = [NSURLSession sharedSession];
    NSURLSessionDataTask *task = [session dataTaskWithRequest:request completionHandler:^(NSData * _Nullable data, NSURLResponse * _Nullable response, NSError * _Nullable error) {
        
    }];
    [task resume];
代码没问题，拷贝运行如上代码

会回调闪退，严重会影响App功能
最新版本。

**Comment by jezzmemo** [comment]
谢谢了，setObject:forKeyedSubscript:的hook有点问题，如果value为nil时是可以的，只是删除了对应的key,尽快修复上传
