### ISSUE TITLE
YBImageBrowser崩溃100%

### ISSUE THREAD

**Issue by hkjin** [jezzmemo/JJException#68]
**Describe the bug**

**To Reproduce**
在多张图片放大浏览退出yb时，会崩溃在下面的位置
`- (void)cleanObservers{
    for (KVOObjectItem* item in self.observers) {
        [self.whichObject removeObserver:item.observer forKeyPath:item.keyPath];
        
    }
    @synchronized (self) {
        [self.observers removeAllObjects];
    }
}
`

**Please complete the following information**
 - Device: [iPhone6plus]
 - OS: [iOS12.1.4]

**Comment by hkjin** [comment]
看来这个框架不维护了 。。。放弃

**Comment by jezzmemo** [comment]
@hkjin 不好意思，最近比较忙，等有时间会立马解决的

**Comment by jezzmemo** [comment]
@hkjin 问题我已经重现，将在这周内修复
