### ISSUE TITLE
NSMutableArray+MutableArrayHook的hookAddObject:问题

### ISSUE THREAD

**Issue by beydeng** [jezzmemo/JJException#71]
使用pod 进行导入库的时候，会出现这个错误。而且很多。如果关闭崩溃那个属性的话，不影响正常使用，请问是什么原因，如何解决

**Comment by jezzmemo** [comment]
关闭哪个属性？

**Comment by beydeng** [comment]
将 exceptionWhenTerminate 设置为NO的时候。
这个错误，好像很多地方出现。
019-08-22 14:06:27.515375+0800 XiaobanParent[708:96556] JJException Type:8
2019-08-22 14:06:27.515408+0800 XiaobanParent[708:96556] JJException Description:NSMutableArray setObject invalid object:com.apple.UIKit.scroll.velocity.interactive.vertical.0201_0300 atIndexedSubscript:2 total:0
2019-08-22 14:06:27.515595+0800 XiaobanParent[708:96556] JJException Extra info:(null)
2019-08-22 14:06:27.516266+0800 XiaobanParent[708:96556] JJException CallStack:[
"0   XiaobanParent                       0x000000010115ed84 -[JJExceptionProxy handleCrashException:exceptionCategory:extraInfo:] + 140",
"1   XiaobanParent                       0x000000010115e934 _Z20handleCrashException24JJExceptionGuardCategoryP8NSString + 124",
"2   XiaobanParent                       0x0000000101161ad0 -[NSMutableArray(MutableArrayHook) hookSetObject:atIndexedSubscript:] + 252",
"3   UIKitCore                           0x00000001f2334df8 <redacted> + 1480",
"4   UIKitCore                           0x00000001f2336898 <redacted> + 68",
"5   libdispatch.dylib                   0x0000000103454dc8 _dispatch_client_callout + 16",
"6   libdispatch.dylib                   0x0000000103456e28 _dispatch_once_callout + 84",
"7   UIKitCore                           0x00000001f233684c <redacted> + 56",
"8   UIKitCore                           0x00000001f23d5d78 <redacted> + 1572",
"9   UIKitCore                           0x00000001f1bbfa38 <redacted> + 64",
"10  UIKitCore                           0x00000001f1bc8054 <redacted> + 124",
"11  UIKitCore                           0x00000001f1bc58d8 <redacted> + 320",
"12  UIKitCore                           0x00000001f1bc4dc0 <redacted> + 764",
"13  UIKitCore                           0x00000001f1bb80c8 <redacted> + 1096",
"14  UIKitCore                           0x00000001f1bb7c34 <redacted> + 384",
"15  UIKitCore                           0x00000001f1bb7a04 <redacted> + 204",
"16  UIKitCore                           0x00000001f1fe53d4 <redacted> + 3128",
"17  XiaobanParent                       0x0000000101fee9c0 -[UIWindow(BaiduMobStatWindow) mtjSendEvent:] + 3872",
"18  UIKitCore                           0x00000001f1fc46ec <redacted> + 340",
"19  UIKitCore                           0x00000001f209057c <redacted> + 1620",
"20  UIKitCore                           0x00000001f2092f74 <redacted> + 4740",
"21  UIKitCore                           0x00000001f208ba64 <redacted> + 152",
"22  CoreFoundation                      0x00000001c4eb41cc <redacted> + 24",
"23  CoreFoundation                      0x00000001c4eb414c <redacted> + 88",
"24  CoreFoundation                      0x00000001c4eb3a30 <redacted> + 176",
"25  CoreFoundation                      0x00000001c4eae8fc <redacted> + 1040",
"26  CoreFoundation                      0x00000001c4eae1cc CFRunLoopRunSpecific + 436",
"27  GraphicsServices                    0x00000001c7125584 GSEventRunModal + 100",
"28  UIKitCore                           0x00000001f1fa9054 UIApplicationMain + 212",
"29  XiaobanParent                       0x00000001010c8aa0 main + 124",
"30  libdyld.dylib                       0x00000001c496ebb4 <redacted> + 4"

**Comment by jezzmemo** [comment]
这个错误是你用了错误的下标才显示出来的，exceptionWhenTerminate的作用是控制抛不抛异常的开关，atIndexedSubscript:2 total:0，表示数组的长度为零，但是你用了下标2

**Comment by isdotjim** [comment]
搭个车...
想邀请Repo作者来w3c.group创建项目的对应小组。w3c.group是类似知识星球的社群工具，小组可设置为付费且有赞助功能，同时也是一个区块链主导的创作者社区。这是相关介绍：
http://t.cn/Ai1vLcCU
http://t.cn/Ai1vLcCG
http://t.cn/Ai1vLcCA
