### ISSUE TITLE
iOS JJException crash

### ISSUE THREAD

**Issue by zhangduyu** [jezzmemo/JJException#72]
**Describe the bug**
您好, 我APP 的 crash 收集工具收集到了一个 crash, 需要您帮忙看一下.

Crashed: com.apple.main-threadEXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x00000000010f0210 Raw Text
--
0 | libobjc.A.dylib | objc_msgSend + 16
**1 | Chope | NSObject+KVOCrash.m line 200-[JJObserverContainer cleanObservers] + 200
2 | Chope | NSObject+SwizzleHook.m line 151__jj_swizzleDeallocIfNeeded_block_invoke_3 + 151**
3 | libobjc.A.dylib | objc_release + 140
28 | libdyld.dylib | <redacted> + 4

我不确定这个 crash 是 JJException 库导致的, 还是 JJException 收集的.

谢谢.

**To Reproduce**
Don't know how to reproduce.

**Please complete the following information**
 - Device: All kinds of devices
 - OS: iOS 12.3.1 - iOS 12.4.0
 - Version: JJException 0.2.4

**Comment by jezzmemo** [comment]
麻烦升级到0.2.5版本，观察一段时间，这个bug已经修复过

**Comment by zhangduyu** [comment]
好的, 谢谢
