### ISSUE TITLE
After Using JJException, many crashes " WebThread EXC_BREAKPOINT" occurred.

### ISSUE THREAD

**Issue by YanxiFeng** [jezzmemo/JJException#73]
I'm facing a bit of crashes after using Jjexception. I don't know is there a relation with it.
0	WebCore	bmalloc::IsoAllocator<bmalloc::IsoConfig<184u> >::allocateSlow(bool) + 252
1   WebCore	bmalloc::IsoAllocator<bmalloc::IsoConfig<184u> >::allocateSlow(bool) + 72
2	WebCore	WebCore::RenderElement::createFor(WebCore::Element&, WebCore::RenderStyle&&, WebCore::RenderElement::RendererCreationType) + 384
3	WebCore	WebCore::RenderTreeUpdater::createRenderer(WebCore::Element&, WebCore::RenderStyle&&) + 652
4	WebCore	WebCore::RenderTreeUpdater::updateElementRenderer(WebCore::Element&, WebCore::Style::ElementUpdate const&) + 732
5	WebCore	WebCore::RenderTreeUpdater::updateRenderTree(WebCore::ContainerNode&) + 1080
6	WebCore	WebCore::RenderTreeUpdater::commit(std::__1::unique_ptr<WebCore::Style::Update const, std::__1::default_delete<WebCore::Style::Update const> >) + 540
7	WebCore	WebCore::Document::resolveStyle(WebCore::Document::ResolveStyleType) + 1028
8	WebCore	WebCore::Document::updateStyleIfNeeded() + 428
9	WebCore	WebCore::ThreadTimers::sharedTimerFiredInternal() + 216
10	WebCore	WebCore::timerFired(__CFRunLoopTimer*, void*) + 28
11	CoreFoundation __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 28
12	CoreFoundation	__CFRunLoopDoTimer + 864
13	CoreFoundation	__CFRunLoopDoTimers + 248
14	CoreFoundation	__CFRunLoopRun + 1844
15	CoreFoundation	CFRunLoopRunSpecific + 436
16	WebCore	RunWebThread(void*) + 600
17	libsystem_pthread.dylib	_pthread_body + 128
18	libsystem_pthread.dylib	_pthread_start + 44
19  libsystem_pthread.dylib	thread_start + 4

**Comment by jezzmemo** [comment]
这个日志完全看不出跟JJException相关，有没跟JJException相关的日志，这是你现场遇到的？还是日志上传上来的？

**Comment by YanxiFeng** [comment]
Fabric日志上传的，应该是跟JJException无关，但是是加了以后才大量出现的，只能往这方面联想了。。

**Comment by jezzmemo** [comment]
是不是你们加入比较多H5的业务，你再观察一段时间，应该是与JJException无关

**Comment by YanxiFeng** [comment]
确认是UIWebview的问题，换成WKWebview就没有再出现了
