### ISSUE TITLE
bugly定位到代码

### ISSUE THREAD

**Issue by gyyxiaogao** [jezzmemo/JJException#74]
![图片](https://user-images.githubusercontent.com/16957066/69813377-04b4af80-122d-11ea-939c-e09a2ff99e51.png)

**Comment by gyyxiaogao** [comment]
![图片](https://user-images.githubusercontent.com/16957066/69813683-a9cf8800-122d-11ea-855b-6134d6f0da8d.png)

**Comment by jezzmemo** [comment]
麻烦把详细点的callstack信息帖出来，这样我好完整定位，修复并验证

**Comment by gyyxiaogao** [comment]
![图片](https://user-images.githubusercontent.com/16957066/69838452-96a0d480-128e-11ea-80fd-675242c7a494.png)

**Comment by gyyxiaogao** [comment]
![图片](https://user-images.githubusercontent.com/16957066/69838553-07e08780-128f-11ea-97a7-0e1be2b14b41.png)

**Comment by jezzmemo** [comment]
你的工程里有没Timer的东西，或者说你觉得比较特殊的，代码片段给我看看，这边复现不了

**Comment by gyyxiaogao** [comment]
就一个很普通的定时器,但是引用定时器的那个页面一直都没有释放.你这个对定时器无法释放支持的还不是很友好吧.

**Comment by jezzmemo** [comment]
不知道你本地有没JJException的demo工程，这里面有对Timer的测试代码的，里面的测试代码就是Timer的常规使用，有时间你可以运行下，看看是不是环境不一样导致的

**Comment by jezzmemo** [comment]
NSMutableAttributedString这个问题应该是系统的问题吧，我之前也有遇到iOS9遇到很莫名的闪退，能否向上回溯，看看那个业务点用到了NSMutableAttributedString
