### ISSUE TITLE
预览文件后，点击右上角的分享按钮后，报错：Thread 1: EXC_BAD_ACCESS (code=1, address=0x20)

### ISSUE THREAD

**Issue by lonelinessRedRain-One** [jezzmemo/JJException#78]
![image](https://user-images.githubusercontent.com/32118873/71945510-f7162080-3201-11ea-8fef-184681b97eb2.png)
![image](https://user-images.githubusercontent.com/32118873/71945560-1f9e1a80-3202-11ea-9c0e-1fe4f055bef2.png)

**Comment by lonelinessRedRain-One** [comment]
+ (void)jj_swizzleZombie{
    [self jj_swizzleInstanceMethod:@selector(dealloc) withSwizzleMethod:@selector(hookDealloc)];
}

- (void)hookDealloc{
    Class currentClass = self.class;
    
    //Check black list
    if (![[[JJExceptionProxy shareExceptionProxy] blackClassesSet] containsObject:currentClass]) {
        [self hookDealloc];**这里报错：****### Thread 1: EXC_BAD_ACCESS (code=1, address=0x20)**
        return;
    }
    
    //Check the array max size
    //TODO:Real remove less than MAX_ARRAY_SIZE
    if ([JJExceptionProxy shareExceptionProxy].currentClassSize > MAX_ARRAY_SIZE) {
        id object = [[JJExceptionProxy shareExceptionProxy] objectFromCurrentClassesSet];
        [[JJExceptionProxy shareExceptionProxy] removeCurrentZombieClass:object_getClass(object)];
        object?free(object):nil;
    }
    
    objc_destructInstance(self);
    object_setClass(self, [JJZombieSub class]);
    [[JJExceptionProxy shareExceptionProxy] addCurrentZombieClass:currentClass];
}

**Comment by lonelinessRedRain-One** [comment]
@jezzmemo

**Comment by jezzmemo** [comment]
能否说下你当前的环境和你的测试片段代码，这样我好复现这个问题

**Comment by lonelinessRedRain-One** [comment]
模拟器，真机调试，真机这三种环境都有这个问题！！出现这个问题是在我预览文件后，右上角有个系统自带的分享按钮，点击那个按钮后，弹出隔空投送菜单(可分享到手机上的其他软件)，这个时候就报错了，所以报错关联的代码是系统的代码，跟我自己写的代码没有关系。你应该看看你的代码跟系统的分享功能有什么冲突。如果实在是要看我预览文件的代码，你再给我回个消息，我白天再给你，晚上
无法提供，不好意思哈
在2020年01月08日 15:52，jezz 写道：

能否说下你当前的环境和你的测试片段代码，这样我好复现这个问题

**Comment by lonelinessRedRain-One** [comment]
如何了？




在2020年01月08日 19:22，高志炎 写道：
模拟器，真机调试，真机这三种环境都有这个问题！！出现这个问题是在我预览文件后，右上角有个系统自带的分享按钮，点击那个按钮后，弹出隔空投送菜单(可分享到手机上的其他软件)，这个时候就报错了，所以报错关联的代码是系统的代码，跟我自己写的代码没有关系。你应该看看你的代码跟系统的分享功能有什么冲突。如果实在是要看我预览文件的代码，你再给我回个消息，我白天再给你，晚上
无法提供，不好意思哈
在2020年01月08日 15:52，jezz 写道：

能否说下你当前的环境和你的测试片段代码，这样我好复现这个问题

**Comment by lonelinessRedRain-One** [comment]
不好意思，我发现是我这边的问题。打扰你了




在2020年01月08日 19:22，高志炎 写道：
模拟器，真机调试，真机这三种环境都有这个问题！！出现这个问题是在我预览文件后，右上角有个系统自带的分享按钮，点击那个按钮后，弹出隔空投送菜单(可分享到手机上的其他软件)，这个时候就报错了，所以报错关联的代码是系统的代码，跟我自己写的代码没有关系。你应该看看你的代码跟系统的分享功能有什么冲突。如果实在是要看我预览文件的代码，你再给我回个消息，我白天再给你，晚上
无法提供，不好意思哈
在2020年01月08日 15:52，jezz 写道：

能否说下你当前的环境和你的测试片段代码，这样我好复现这个问题
