### ISSUE TITLE
kvo crash

### ISSUE THREAD

**Issue by hc2088** [jezzmemo/JJException#8]
//     使用参数NSKeyValueObservingOptionInitial就会崩溃   
  //     仅使用NSKeyValueObservingOptionNew|NSKeyValueObservingOptionPrior|NSKeyValueObservingOptionOld这些参数不会发生崩溃

    [self addObserver:self forKeyPath:@"test1" options:NSKeyValueObservingOptionNew|NSKeyValueObservingOptionInitial context:nil];

Terminating app due to uncaught exception 'NSUnknownKeyException', reason: '[<PushViewController 0x7ffa3fc013b0> addObserver:<PushViewController 0x7ffa3fc013b0> forKeyPath:@"test1" options:5 context:0x0] was sent to an object that is not KVC-compliant for the "test1" property.'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010476429b __exceptionPreprocess + 331
	1   libobjc.A.dylib                     0x0000000103d00735 objc_exception_throw + 48
	2   CoreFoundation                      0x00000001047640f5 +[NSException raise:format:] + 197
	3   Foundation                          0x000000010373e7c5 -[NSObject(NSKeyValueObserverRegistration) addObserver:forKeyPath:options:context:] + 458
	4   JJException                         0x00000001033c359a -[NSObject(KVOCrash) hookAddObserver:forKeyPath:options:context:] + 442

**Comment by jezzmemo** [comment]
这个不是程序有问题，而是我的那个demo写的有点瑕疵，你在当前的controller加一个test1属性,就不会crash了
```
@property(nonatomic,readwrite,copy)NSString* test1;
```
@hc2088

**Comment by jezzmemo** [comment]
其实这种错误我也可以处理，但是想想这种属性都没写的错误，还是需要显示的抛出来，因为太过明显，证明测试也没覆盖到，所以这种错误显示抛出比较合理
