### ISSUE TITLE
使用之后，模拟APP不闪退，没有上传到友盟上面

### ISSUE THREAD

**Issue by GKTian** [jezzmemo/JJException#87]
这样使用的：
[JJException configExceptionCategory:JJExceptionGuardUnrecognizedSelector | JJExceptionGuardDictionaryContainer | JJExceptionGuardArrayContainer | JJExceptionGuardNSTimer | JJExceptionGuardNSNotificationCenter | JJExceptionGuardNSStringContainer];
 [JJException startGuardException];
版本 0.2.8
@jezzmemo

**Comment by jezzmemo** [comment]
友盟需要自己集成，[可以参考Bugly集成](https://github.com/jezzmemo/JJException#faq)

**Comment by GKTian** [comment]
友盟已经集成了，之前是崩溃了不能使用APP，友盟可以统计到。这次是为了崩溃后APP还能继续使用，在上线前，模拟了下，APP不闪退，就是友盟没有上报。还需要自己上报到友盟吗？

**Comment by GKTian** [comment]
友盟好像没有手动上报崩溃的方法

**Comment by GKTian** [comment]
> 友盟需要自己集成，[可以参考Bugly集成](https://github.com/jezzmemo/JJException#faq)
友盟好像没有手动上报崩溃的方法

**Comment by GKTian** [comment]
@jezzmemo  友盟没有手动上报崩溃信息的方法，

**Comment by jezzmemo** [comment]
可以用event来做，只是要区分事件和异常事件

**Comment by GKTian** [comment]
用友盟的事件统计不太好，统计不到崩溃次数和崩溃率。

**Comment by GKTian** [comment]
现在想APP既不崩溃，友盟还能捕捉到崩溃信息。
