### ISSUE TITLE
NStimer崩溃

### ISSUE THREAD

**Issue by pstkqzy** [jezzmemo/JJException#89]
我在项目中使用了SDCycleScrollView 会出现崩溃，SDCycleScrollView调用automaticScroll方法时会崩到NSTimer+CleanTimer.m里，报错代码为'''NSMethodSignature* signature = [NSMethodSignature methodSignatureForSelector:self.selector];
        NSInvocation* invocation = [NSInvocation invocationWithMethodSignature:signature];'''
报错描述：+[NSInvocation _invocationWithMethodSignature:frame:]: method signature argument cannot be nil
报错原因：signature为nil，导致崩溃
我使用的SDCycleScrollView为1.65版本

**Comment by jezzmemo** [comment]
有没相应的测试代码？这样我快速复现并修复，还有就是你使用的那个版本的JJException

**Comment by pstkqzy** [comment]
@jezzmemo 
[test.zip](https://github.com/jezzmemo/JJException/files/5159845/test.zip)

**Comment by pstkqzy** [comment]
@jezzmemo  这个好像崩的概率很高，希望您看一下

**Comment by jezzmemo** [comment]
@pstkqzy 问题已定位，我将尽快更新
