### ISSUE TITLE
testUndefineSelector crash

### ISSUE THREAD

**Issue by hc2088** [jezzmemo/JJException#9]
```
@protocol SomeProtocol<NSObject>
@optional
-(void)testUndefineSelector;
@end
@interface ViewController ()<JJExceptionHandle,SomeProtocol>
@end
```

`[self performSelector:@selector(testUndefineSelector)];`

崩溃了：

2018-09-30 16:11:02.955 JJException[22830:279892] -[ViewController testUndefineSelector]: unrecognized selector sent to instance 0x7f8aaff863c0
2018-09-30 16:11:02.961 JJException[22830:279892] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[ViewController testUndefineSelector]: unrecognized selector sent to instance 0x7f8aaff863c0'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010d6e7f65 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x000000010d161deb objc_exception_throw + 48
	2   CoreFoundation                      0x000000010d6f058d -[NSObject(NSObject) doesNotRecognizeSelector:] + 205
	3   CoreFoundation                      0x000000010d63dd97 ___forwarding___ + 487
	4   CoreFoundation                      0x000000010d63db28 _CF_forwarding_prep_0 + 120
	5   JJException                         0x000000010cc42003 -[ViewController testUnrecognizedSelector] + 51
	6   JJException                         0x000000010cc41d7c -[ViewController testArrayDictionaryUnrecognizedSelector] + 44

**Comment by jezzmemo** [comment]
如果申明Protocol,我在编译看机器码，编译器会把协议的方法都加入到当前类里，但是没有对应的具体实现，所以在查找方法签名的时候，是可以找到的，但是没有具体实现，所以需要验证下方法是否存在。
@hc2088

**Comment by jezzmemo** [comment]
国庆之前处理的方法不对，因为我们无法分辨方法是否存在，还有方法是否被父类重写，后面我还是调整了Unrecognized Selector方式，具体的[实现细节](https://github.com/jezzmemo/JJException/blob/master/JJExceptionPrinciple.md)在这里__2018-10-7__
