### ISSUE TITLE
开启后，NSTimer定时针失效

### ISSUE THREAD

**Issue by xhm121** [jezzmemo/JJException#90]
**Describe the bug**
OC版本中的
PushViewController.m文件中 - (void)testTimer方法，将_t 的target由self 变成[HMTimerProxy timerProxyWithObject:self] ，如下:
    _t = [NSTimer scheduledTimerWithTimeInterval:0.1 target:[HMTimerProxy timerProxyWithObject:self] selector:@selector(scheduledMethod:) userInfo:nil repeats:YES];

HMTimerProxy是我自己的创建的一个对象，继承自NSObject

问题: 将定时器的target由self变成一个自己创建的第三者，就会导致定时器失效

#import "HMTimerProxy.h"

@interface HMTimerProxy ()

@property (nonatomic, weak) id weakobject;

@end

@implementation HMTimerProxy

 + (instancetype)timerProxyWithObject:(id)weakObject {
    HMTimerProxy *timerProxy = [[HMTimerProxy alloc] init];
    timerProxy.weakobject = weakObject;
    return timerProxy;
}

 - (NSMethodSignature *)methodSignatureForSelector:(SEL)aSelector {
    if (self.weakobject) {
        return [self.weakobject methodSignatureForSelector:aSelector];
    } else {
        return [super methodSignatureForSelector:aSelector];
    }
}

 - (void)forwardInvocation:(NSInvocation *)anInvocation {
    SEL selector = anInvocation.selector;
    if ([self.weakobject respondsToSelector:selector]) {
        [anInvocation invokeWithTarget:self.weakobject];
    } else {
        [super forwardInvocation:anInvocation];
    }
}

**Comment by jezzmemo** [comment]
明白你的问题了，这是因为NSTimer的中间者做了selector的验证，它需要显示的写对应的方法且存在，不支持你这种中间转发的方式

**Comment by pstkqzy** [comment]
@xhm121 你这个类内部实现不太对，你可以看看YYTextWeakProxy内部的实现

**Comment by xhm121** [comment]
> 明白你的问题了，这是因为NSTimer的中间者做了selector的验证，它需要显示的写对应的方法且存在，不支持你这种中间转发的方式

**Comment by xhm121** [comment]
> 明白你的问题了，这是因为NSTimer的中间者做了selector的验证，它需要显示的写对应的方法且存在，不支持你这种中间转发的方式

我看了市面上好几套防崩溃的框架，都会出现这个问题

**Comment by xhm121** [comment]
> @xhm121 你这个类内部实现不太对，你可以看看YYTextWeakProxy内部的实现

嗯，我这个是继承自NSObject,不是NSProxy。我是基于消息转发的第三步去做的。

**Comment by ZC-Hank** [comment]
直接使用YYTextWeakProxy 定时器还是失效

self.timer = [NSTimer scheduledTimerWithTimeInterval:1.0 target:[YYTextWeakProxy proxyWithTarget:self] selector:@selector(timerEvent1:) userInfo:nil repeats:YES];
//    self.timer = [NSTimer scheduledTimerWithTimeInterval:1.0 target:self selector:@selector(timerEvent1:) userInfo:nil repeats:YES];
    [[NSRunLoop currentRunLoop] addTimer:self.timer forMode:NSRunLoopCommonModes];

#import <Foundation/Foundation.h>

NS_ASSUME_NONNULL_BEGIN

/**
 A proxy used to hold a weak object.
 It can be used to avoid retain cycles, such as the target in NSTimer or CADisplayLink.
 
 sample code:
 
     @implementation MyView {
        NSTimer *_timer;
     }
     
     - (void)initTimer {
        YYTextWeakProxy *proxy = [YYTextWeakProxy proxyWithTarget:self];
        _timer = [NSTimer timerWithTimeInterval:0.1 target:proxy selector:@selector(tick:) userInfo:nil repeats:YES];
     }
     
     - (void)tick:(NSTimer *)timer {...}
     @end
 */
@interface YYTextWeakProxy : NSProxy

/**
 The proxy target.
 */
@property (nullable, nonatomic, weak, readonly) id target;

/**
 Creates a new weak proxy for target.
 
 @param target Target object.
 
 @return A new proxy object.
 */
- (instancetype)initWithTarget:(id)target;

/**
 Creates a new weak proxy for target.
 
 @param target Target object.
 
 @return A new proxy object.
 */
+ (instancetype)proxyWithTarget:(id)target;

@end

#import "YYTextWeakProxy.h"


@implementation YYTextWeakProxy

- (instancetype)initWithTarget:(id)target {
    _target = target;
    return self;
}

+ (instancetype)proxyWithTarget:(id)target {
    return [[YYTextWeakProxy alloc] initWithTarget:target];
}

- (id)forwardingTargetForSelector:(SEL)selector {
    return _target;
}

- (void)forwardInvocation:(NSInvocation *)invocation {
    void *null = NULL;
    [invocation setReturnValue:&null];
}

- (NSMethodSignature *)methodSignatureForSelector:(SEL)selector {
    return [NSObject instanceMethodSignatureForSelector:@selector(init)];
}

- (BOOL)respondsToSelector:(SEL)aSelector {
    return [_target respondsToSelector:aSelector];
}

- (BOOL)isEqual:(id)object {
    return [_target isEqual:object];
}

- (NSUInteger)hash {
    return [_target hash];
}

- (Class)superclass {
    return [_target superclass];
}

- (Class)class {
    return [_target class];
}

- (BOOL)isKindOfClass:(Class)aClass {
    return [_target isKindOfClass:aClass];
}

- (BOOL)isMemberOfClass:(Class)aClass {
    return [_target isMemberOfClass:aClass];
}

- (BOOL)conformsToProtocol:(Protocol *)aProtocol {
    return [_target conformsToProtocol:aProtocol];
}

- (BOOL)isProxy {
    return YES;
}

- (NSString *)description {
    return [_target description];
}

- (NSString *)debugDescription {
    return [_target debugDescription];
}

@end

**Comment by ZC-Hank** [comment]
> > @xhm121 你这个类内部实现不太对，你可以看看YYTextWeakProxy内部的实现
> 
> 嗯，我这个是继承自NSObject,不是NSProxy。我是基于消息转发的第三步去做的。

你的问题解决了吗？
我直接下载使用YYTextWeakProxy ，定时器还是失效。
